// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meal_plan.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getMealPlan = `-- name: GetMealPlan :one
SELECT id, week_start, status, created_at
FROM meal_plan WHERE id = $1
`

func (q *Queries) GetMealPlan(ctx context.Context, id uuid.UUID) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getMealPlan, id)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.WeekStart,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateMealPlan = `-- name: GetOrCreateMealPlan :one
INSERT INTO meal_plan (id, week_start, status, created_at)
VALUES ($1, $2, 'draft', $3)
ON CONFLICT (week_start) DO UPDATE SET week_start = EXCLUDED.week_start
RETURNING id, week_start, status, created_at
`

type GetOrCreateMealPlanParams struct {
	ID        uuid.UUID `json:"id"`
	WeekStart time.Time `json:"week_start"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetOrCreateMealPlan(ctx context.Context, arg GetOrCreateMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateMealPlan, arg.ID, arg.WeekStart, arg.CreatedAt)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.WeekStart,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertCandidate = `-- name: InsertCandidate :exec
INSERT INTO meal_plan_candidate (id, plan_id, slot_date, slot_kind, recipe_ref_id, score, breakdown, feasible, rank)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertCandidateParams struct {
	ID          uuid.UUID       `json:"id"`
	PlanID      uuid.UUID       `json:"plan_id"`
	SlotDate    time.Time       `json:"slot_date"`
	SlotKind    string          `json:"slot_kind"`
	RecipeRefID uuid.UUID       `json:"recipe_ref_id"`
	Score       float64         `json:"score"`
	Breakdown   json.RawMessage `json:"breakdown"`
	Feasible    bool            `json:"feasible"`
	Rank        int32           `json:"rank"`
}

func (q *Queries) InsertCandidate(ctx context.Context, arg InsertCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertCandidate,
		arg.ID,
		arg.PlanID,
		arg.SlotDate,
		arg.SlotKind,
		arg.RecipeRefID,
		arg.Score,
		arg.Breakdown,
		arg.Feasible,
		arg.Rank,
	)
	return err
}

const insertShoppingRequirement = `-- name: InsertShoppingRequirement :exec
INSERT INTO shopping_requirement (plan_id, ingredient_id, quantity, unit, acceptable_forms, preferred_form)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (plan_id, ingredient_id) DO UPDATE
SET quantity = EXCLUDED.quantity,
    unit = EXCLUDED.unit,
    acceptable_forms = EXCLUDED.acceptable_forms,
    preferred_form = EXCLUDED.preferred_form
`

type InsertShoppingRequirementParams struct {
	PlanID          uuid.UUID      `json:"plan_id"`
	IngredientID    uuid.UUID      `json:"ingredient_id"`
	Quantity        string         `json:"quantity"`
	Unit            string         `json:"unit"`
	AcceptableForms []string       `json:"acceptable_forms"`
	PreferredForm   sql.NullString `json:"preferred_form"`
}

func (q *Queries) InsertShoppingRequirement(ctx context.Context, arg InsertShoppingRequirementParams) error {
	_, err := q.db.ExecContext(ctx, insertShoppingRequirement,
		arg.PlanID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
		pq.Array(arg.AcceptableForms),
		arg.PreferredForm,
	)
	return err
}

const listCandidates = `-- name: ListCandidates :many
SELECT id, plan_id, slot_date, slot_kind, recipe_ref_id, score, breakdown, feasible, rank
FROM meal_plan_candidate
WHERE plan_id = $1
ORDER BY slot_date, rank
`

type ListCandidatesRow struct {
	ID          uuid.UUID       `json:"id"`
	PlanID      uuid.UUID       `json:"plan_id"`
	SlotDate    time.Time       `json:"slot_date"`
	SlotKind    string          `json:"slot_kind"`
	RecipeRefID uuid.UUID       `json:"recipe_ref_id"`
	Score       float64         `json:"score"`
	Breakdown   json.RawMessage `json:"breakdown"`
	Feasible    bool            `json:"feasible"`
	Rank        int32           `json:"rank"`
}

func (q *Queries) ListCandidates(ctx context.Context, planID uuid.UUID) ([]ListCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCandidates, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.SlotDate,
			&i.SlotKind,
			&i.RecipeRefID,
			&i.Score,
			&i.Breakdown,
			&i.Feasible,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT plan_id, slot_date, slot_kind, recipe_ref_id, decided_at
FROM meal_plan_decision
WHERE plan_id = $1
ORDER BY slot_date, slot_kind
`

type ListDecisionsRow struct {
	PlanID      uuid.UUID `json:"plan_id"`
	SlotDate    time.Time `json:"slot_date"`
	SlotKind    string    `json:"slot_kind"`
	RecipeRefID uuid.UUID `json:"recipe_ref_id"`
	DecidedAt   time.Time `json:"decided_at"`
}

func (q *Queries) ListDecisions(ctx context.Context, planID uuid.UUID) ([]ListDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDecisions, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionsRow
	for rows.Next() {
		var i ListDecisionsRow
		if err := rows.Scan(
			&i.PlanID,
			&i.SlotDate,
			&i.SlotKind,
			&i.RecipeRefID,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlans = `-- name: ListMealPlans :many
SELECT id, week_start, status, created_at
FROM meal_plan
ORDER BY week_start DESC
`

func (q *Queries) ListMealPlans(ctx context.Context) ([]MealPlan, error) {
	rows, err := q.db.QueryContext(ctx, listMealPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealPlan
	for rows.Next() {
		var i MealPlan
		if err := rows.Scan(
			&i.ID,
			&i.WeekStart,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingRequirements = `-- name: ListShoppingRequirements :many
SELECT plan_id, ingredient_id, quantity, unit, acceptable_forms, preferred_form
FROM shopping_requirement
WHERE plan_id = $1
ORDER BY ingredient_id
`

type ListShoppingRequirementsRow struct {
	PlanID          uuid.UUID      `json:"plan_id"`
	IngredientID    uuid.UUID      `json:"ingredient_id"`
	Quantity        string         `json:"quantity"`
	Unit            string         `json:"unit"`
	AcceptableForms []string       `json:"acceptable_forms"`
	PreferredForm   sql.NullString `json:"preferred_form"`
}

func (q *Queries) ListShoppingRequirements(ctx context.Context, planID uuid.UUID) ([]ListShoppingRequirementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingRequirements, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShoppingRequirementsRow
	for rows.Next() {
		var i ListShoppingRequirementsRow
		if err := rows.Scan(
			&i.PlanID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			pq.Array(&i.AcceptableForms),
			&i.PreferredForm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDecision = `-- name: SetDecision :exec
INSERT INTO meal_plan_decision (plan_id, slot_date, slot_kind, recipe_ref_id, decided_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (plan_id, slot_date, slot_kind) DO UPDATE
SET recipe_ref_id = EXCLUDED.recipe_ref_id,
    decided_at = EXCLUDED.decided_at
`

type SetDecisionParams struct {
	PlanID      uuid.UUID `json:"plan_id"`
	SlotDate    time.Time `json:"slot_date"`
	SlotKind    string    `json:"slot_kind"`
	RecipeRefID uuid.UUID `json:"recipe_ref_id"`
	DecidedAt   time.Time `json:"decided_at"`
}

func (q *Queries) SetDecision(ctx context.Context, arg SetDecisionParams) error {
	_, err := q.db.ExecContext(ctx, setDecision,
		arg.PlanID,
		arg.SlotDate,
		arg.SlotKind,
		arg.RecipeRefID,
		arg.DecidedAt,
	)
	return err
}

const setMealPlanStatus = `-- name: SetMealPlanStatus :exec
UPDATE meal_plan SET status = $2 WHERE id = $1
`

type SetMealPlanStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetMealPlanStatus(ctx context.Context, arg SetMealPlanStatusParams) error {
	_, err := q.db.ExecContext(ctx, setMealPlanStatus, arg.ID, arg.Status)
	return err
}
