// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addMealReaction = `-- name: AddMealReaction :exec
INSERT INTO meal_reaction (meal_event_id, person_id, sentiment)
VALUES ($1, $2, $3)
ON CONFLICT (meal_event_id, person_id) DO UPDATE
SET sentiment = EXCLUDED.sentiment
`

type AddMealReactionParams struct {
	MealEventID uuid.UUID `json:"meal_event_id"`
	PersonID    uuid.UUID `json:"person_id"`
	Sentiment   int16     `json:"sentiment"`
}

func (q *Queries) AddMealReaction(ctx context.Context, arg AddMealReactionParams) error {
	_, err := q.db.ExecContext(ctx, addMealReaction, arg.MealEventID, arg.PersonID, arg.Sentiment)
	return err
}

const createMealEvent = `-- name: CreateMealEvent :one
INSERT INTO meal_event (id, recipe_ref_id, served_on, meal_plan_id, meal_plan_slot_date, meal_plan_slot_kind)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateMealEventParams struct {
	ID               uuid.UUID      `json:"id"`
	RecipeRefID      uuid.UUID      `json:"recipe_ref_id"`
	ServedOn         time.Time      `json:"served_on"`
	MealPlanID       uuid.NullUUID  `json:"meal_plan_id"`
	MealPlanSlotDate sql.NullTime   `json:"meal_plan_slot_date"`
	MealPlanSlotKind sql.NullString `json:"meal_plan_slot_kind"`
}

func (q *Queries) CreateMealEvent(ctx context.Context, arg CreateMealEventParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createMealEvent,
		arg.ID,
		arg.RecipeRefID,
		arg.ServedOn,
		arg.MealPlanID,
		arg.MealPlanSlotDate,
		arg.MealPlanSlotKind,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteFavorite = `-- name: DeleteFavorite :exec
DELETE FROM favorite
WHERE scope_type = 'person' AND scope_id = $1 AND recipe_ref_id = $2
`

type DeleteFavoriteParams struct {
	ScopeID     uuid.UUID `json:"scope_id"`
	RecipeRefID uuid.UUID `json:"recipe_ref_id"`
}

func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, deleteFavorite, arg.ScopeID, arg.RecipeRefID)
	return err
}

const getMealEvent = `-- name: GetMealEvent :one
SELECT id, recipe_ref_id, served_on, meal_plan_id, meal_plan_slot_date, meal_plan_slot_kind
FROM meal_event WHERE id = $1
`

type GetMealEventRow struct {
	ID               uuid.UUID      `json:"id"`
	RecipeRefID      uuid.UUID      `json:"recipe_ref_id"`
	ServedOn         time.Time      `json:"served_on"`
	MealPlanID       uuid.NullUUID  `json:"meal_plan_id"`
	MealPlanSlotDate sql.NullTime   `json:"meal_plan_slot_date"`
	MealPlanSlotKind sql.NullString `json:"meal_plan_slot_kind"`
}

func (q *Queries) GetMealEvent(ctx context.Context, id uuid.UUID) (GetMealEventRow, error) {
	row := q.db.QueryRowContext(ctx, getMealEvent, id)
	var i GetMealEventRow
	err := row.Scan(
		&i.ID,
		&i.RecipeRefID,
		&i.ServedOn,
		&i.MealPlanID,
		&i.MealPlanSlotDate,
		&i.MealPlanSlotKind,
	)
	return i, err
}

const getRecipeRating = `-- name: GetRecipeRating :one
SELECT
    COALESCE(AVG(sentiment), 0) AS avg_sentiment,
    COUNT(*) AS count
FROM meal_reaction mr
JOIN meal_event me ON mr.meal_event_id = me.id
WHERE me.recipe_ref_id = $1
`

type GetRecipeRatingRow struct {
	AvgSentiment interface{} `json:"avg_sentiment"`
	Count        int64       `json:"count"`
}

func (q *Queries) GetRecipeRating(ctx context.Context, recipeRefID uuid.UUID) (GetRecipeRatingRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeRating, recipeRefID)
	var i GetRecipeRatingRow
	err := row.Scan(&i.AvgSentiment, &i.Count)
	return i, err
}

const listFavoritesForRecipe = `-- name: ListFavoritesForRecipe :many
SELECT scope_type, scope_id, recipe_ref_id, created_at
FROM favorite
WHERE recipe_ref_id = $1
ORDER BY scope_id
`

func (q *Queries) ListFavoritesForRecipe(ctx context.Context, recipeRefID uuid.UUID) ([]Favorite, error) {
	rows, err := q.db.QueryContext(ctx, listFavoritesForRecipe, recipeRefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Favorite
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(
			&i.ScopeType,
			&i.ScopeID,
			&i.RecipeRefID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealEvents = `-- name: ListMealEvents :many
SELECT id, recipe_ref_id, served_on, meal_plan_id, meal_plan_slot_date, meal_plan_slot_kind
FROM meal_event
WHERE recipe_ref_id = $1
ORDER BY served_on DESC
`

type ListMealEventsRow struct {
	ID               uuid.UUID      `json:"id"`
	RecipeRefID      uuid.UUID      `json:"recipe_ref_id"`
	ServedOn         time.Time      `json:"served_on"`
	MealPlanID       uuid.NullUUID  `json:"meal_plan_id"`
	MealPlanSlotDate sql.NullTime   `json:"meal_plan_slot_date"`
	MealPlanSlotKind sql.NullString `json:"meal_plan_slot_kind"`
}

func (q *Queries) ListMealEvents(ctx context.Context, recipeRefID uuid.UUID) ([]ListMealEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealEvents, recipeRefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealEventsRow
	for rows.Next() {
		var i ListMealEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeRefID,
			&i.ServedOn,
			&i.MealPlanID,
			&i.MealPlanSlotDate,
			&i.MealPlanSlotKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealReactions = `-- name: ListMealReactions :many
SELECT meal_event_id, person_id, sentiment
FROM meal_reaction
WHERE meal_event_id = $1
ORDER BY person_id
`

type ListMealReactionsRow struct {
	MealEventID uuid.UUID `json:"meal_event_id"`
	PersonID    uuid.UUID `json:"person_id"`
	Sentiment   int16     `json:"sentiment"`
}

func (q *Queries) ListMealReactions(ctx context.Context, mealEventID uuid.UUID) ([]ListMealReactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealReactions, mealEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealReactionsRow
	for rows.Next() {
		var i ListMealReactionsRow
		if err := rows.Scan(&i.MealEventID, &i.PersonID, &i.Sentiment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFavorite = `-- name: UpsertFavorite :exec
INSERT INTO favorite (scope_type, scope_id, recipe_ref_id, created_at)
VALUES ('person', $1, $2, $3)
ON CONFLICT (scope_type, scope_id, recipe_ref_id) DO NOTHING
`

type UpsertFavoriteParams struct {
	ScopeID     uuid.UUID `json:"scope_id"`
	RecipeRefID uuid.UUID `json:"recipe_ref_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) UpsertFavorite(ctx context.Context, arg UpsertFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, upsertFavorite, arg.ScopeID, arg.RecipeRefID, arg.CreatedAt)
	return err
}
