// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID           uuid.UUID      `json:"id"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	AuthMethod   string         `json:"auth_method"`
	PersonID     uuid.NullUUID  `json:"person_id"`
	CreatedAt    time.Time      `json:"created_at"`
	LastLoginAt  sql.NullTime   `json:"last_login_at"`
}

type CurrentStoreProductPrice struct {
	OfferID           uuid.UUID `json:"offer_id"`
	StoreID           uuid.UUID `json:"store_id"`
	RetailerProductID uuid.UUID `json:"retailer_product_id"`
	PriceKind         string    `json:"price_kind"`
	Price             string    `json:"price"`
	ObservedAt        time.Time `json:"observed_at"`
	Source            string    `json:"source"`
}

type EffortProfile struct {
	Weekday       int16 `json:"weekday"`
	KitchenEnergy int16 `json:"kitchen_energy"`
}

type ExternalRecipeSource struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	BaseUrl     sql.NullString `json:"base_url"`
	LicenseNote sql.NullString `json:"license_note"`
	Decision    string         `json:"decision"`
	Enabled     bool           `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Favorite struct {
	ScopeType   string    `json:"scope_type"`
	ScopeID     uuid.UUID `json:"scope_id"`
	RecipeRefID uuid.UUID `json:"recipe_ref_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Household struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type HouseholdMembership struct {
	HouseholdID uuid.UUID     `json:"household_id"`
	PersonID    uuid.UUID     `json:"person_id"`
	JoinedAt    time.Time     `json:"joined_at"`
	EndedAt     sql.NullTime  `json:"ended_at"`
	EndedBy     uuid.NullUUID `json:"ended_by"`
}

type Ingredient struct {
	ID           uuid.UUID     `json:"id"`
	Slug         string        `json:"slug"`
	Display      string        `json:"display"`
	MergedIntoID uuid.NullUUID `json:"merged_into_id"`
}

type IngredientAlias struct {
	ID           uuid.UUID     `json:"id"`
	HouseholdID  uuid.NullUUID `json:"household_id"`
	Alias        string        `json:"alias"`
	IngredientID uuid.UUID     `json:"ingredient_id"`
	CreatedAt    time.Time     `json:"created_at"`
}

type IngredientExternalRef struct {
	Provider     string         `json:"provider"`
	ExternalID   string         `json:"external_id"`
	IngredientID uuid.UUID      `json:"ingredient_id"`
	GramsPerUnit sql.NullString `json:"grams_per_unit"`
	DefaultForm  sql.NullString `json:"default_form"`
	NeedsReview  bool           `json:"needs_review"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type IngredientForm struct {
	IngredientID uuid.UUID      `json:"ingredient_id"`
	Form         string         `json:"form"`
	Notes        sql.NullString `json:"notes"`
	CreatedAt    time.Time      `json:"created_at"`
}

type IngredientSubstitution struct {
	ID               uuid.UUID      `json:"id"`
	FromIngredientID uuid.UUID      `json:"from_ingredient_id"`
	FromForm         sql.NullString `json:"from_form"`
	ToIngredientID   uuid.UUID      `json:"to_ingredient_id"`
	ToForm           sql.NullString `json:"to_form"`
	Category         string         `json:"category"`
	Ratio            string         `json:"ratio"`
	RetiredAt        sql.NullTime   `json:"retired_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type IngredientUnitConversion struct {
	IngredientID uuid.UUID `json:"ingredient_id"`
	FromUnit     string    `json:"from_unit"`
	ToUnit       string    `json:"to_unit"`
	Factor       string    `json:"factor"`
}

type InventoryEvent struct {
	ID             uuid.UUID      `json:"id"`
	Kind           string         `json:"kind"`
	LotID          uuid.NullUUID  `json:"lot_id"`
	IngredientID   uuid.NullUUID  `json:"ingredient_id"`
	ProductID      uuid.NullUUID  `json:"product_id"`
	FromLocationID uuid.NullUUID  `json:"from_location_id"`
	ToLocationID   uuid.NullUUID  `json:"to_location_id"`
	QuantityDelta  string         `json:"quantity_delta"`
	Reason         sql.NullString `json:"reason"`
	Source         string         `json:"source"`
	RecordedAt     time.Time      `json:"recorded_at"`
}

type InventoryLocation struct {
	ID               uuid.UUID      `json:"id"`
	Slug             string         `json:"slug"`
	HouseholdID      uuid.UUID      `json:"household_id"`
	Name             string         `json:"name"`
	LocationType     sql.NullString `json:"location_type"`
	ParentLocationID uuid.NullUUID  `json:"parent_location_id"`
	ArchivedAt       sql.NullTime   `json:"archived_at"`
}

type InventoryLot struct {
	ID           uuid.UUID     `json:"id"`
	IngredientID uuid.UUID     `json:"ingredient_id"`
	ProductID    uuid.NullUUID `json:"product_id"`
	LocationID   uuid.UUID     `json:"location_id"`
	Quantity     string        `json:"quantity"`
	Unit         string        `json:"unit"`
	Confidence   string        `json:"confidence"`
	BestBefore   sql.NullTime  `json:"best_before"`
	OpenedAt     sql.NullTime  `json:"opened_at"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type MealEvent struct {
	ID               uuid.UUID      `json:"id"`
	RecipeRefID      uuid.UUID      `json:"recipe_ref_id"`
	ServedOn         time.Time      `json:"served_on"`
	CreatedAt        time.Time      `json:"created_at"`
	MealPlanID       uuid.NullUUID  `json:"meal_plan_id"`
	MealPlanSlotDate sql.NullTime   `json:"meal_plan_slot_date"`
	MealPlanSlotKind sql.NullString `json:"meal_plan_slot_kind"`
}

type MealParticipant struct {
	MealEventID uuid.UUID `json:"meal_event_id"`
	PersonID    uuid.UUID `json:"person_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type MealPlan struct {
	ID        uuid.UUID `json:"id"`
	WeekStart time.Time `json:"week_start"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type MealPlanCandidate struct {
	ID          uuid.UUID       `json:"id"`
	PlanID      uuid.UUID       `json:"plan_id"`
	SlotDate    time.Time       `json:"slot_date"`
	RecipeRefID uuid.UUID       `json:"recipe_ref_id"`
	Score       float64         `json:"score"`
	Breakdown   json.RawMessage `json:"breakdown"`
	Feasible    bool            `json:"feasible"`
	Rank        int32           `json:"rank"`
	SlotKind    string          `json:"slot_kind"`
}

type MealPlanDecision struct {
	PlanID      uuid.UUID `json:"plan_id"`
	SlotDate    time.Time `json:"slot_date"`
	RecipeRefID uuid.UUID `json:"recipe_ref_id"`
	DecidedAt   time.Time `json:"decided_at"`
	SlotKind    string    `json:"slot_kind"`
}

type MealReaction struct {
	MealEventID uuid.UUID      `json:"meal_event_id"`
	PersonID    uuid.UUID      `json:"person_id"`
	Sentiment   int16          `json:"sentiment"`
	Note        sql.NullString `json:"note"`
	CreatedAt   time.Time      `json:"created_at"`
}

type MealReview struct {
	MealEventID uuid.UUID      `json:"meal_event_id"`
	PersonID    uuid.UUID      `json:"person_id"`
	Rating      int16          `json:"rating"`
	Note        sql.NullString `json:"note"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Order struct {
	ID              uuid.UUID     `json:"id"`
	ShoppingCartID  uuid.NullUUID `json:"shopping_cart_id"`
	Retailer        string        `json:"retailer"`
	Source          string        `json:"source"`
	OrderedAt       time.Time     `json:"ordered_at"`
	TotalPriceMinor sql.NullInt64 `json:"total_price_minor"`
	Currency        string        `json:"currency"`
}

type OrderItem struct {
	ID                   uuid.UUID      `json:"id"`
	OrderID              uuid.UUID      `json:"order_id"`
	RetailerProductID    string         `json:"retailer_product_id"`
	Quantity             string         `json:"quantity"`
	UnitPrice            sql.NullString `json:"unit_price"`
	TotalPriceMinor      sql.NullInt64  `json:"total_price_minor"`
	Currency             string         `json:"currency"`
	SubstitutedForItemID uuid.NullUUID  `json:"substituted_for_item_id"`
}

type Person struct {
	ID        uuid.UUID     `json:"id"`
	Slug      string        `json:"slug"`
	Name      string        `json:"name"`
	Weight    string        `json:"weight"`
	CreatedAt time.Time     `json:"created_at"`
	AccountID uuid.NullUUID `json:"account_id"`
}

type PersonPreference struct {
	PersonID   uuid.UUID `json:"person_id"`
	Tag        string    `json:"tag"`
	Sentiment  int16     `json:"sentiment"`
	Confidence string    `json:"confidence"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type PersonRestriction struct {
	PersonID   uuid.UUID      `json:"person_id"`
	Tag        string         `json:"tag"`
	Kind       string         `json:"kind"`
	Note       sql.NullString `json:"note"`
	RecordedBy uuid.NullUUID  `json:"recorded_by"`
	RecordedAt time.Time      `json:"recorded_at"`
	ClearedAt  sql.NullTime   `json:"cleared_at"`
	ClearedBy  uuid.NullUUID  `json:"cleared_by"`
}

type PlanningConstraint struct {
	ID     uuid.UUID `json:"id"`
	Kind   string    `json:"kind"`
	Value  string    `json:"value"`
	Active bool      `json:"active"`
}

type PreferenceObservation struct {
	ID         uuid.UUID `json:"id"`
	PersonID   uuid.UUID `json:"person_id"`
	Tag        string    `json:"tag"`
	Sentiment  int16     `json:"sentiment"`
	Source     string    `json:"source"`
	ObservedAt time.Time `json:"observed_at"`
}

type PriceObservation struct {
	ID                  uuid.UUID `json:"id"`
	StoreProductOfferID uuid.UUID `json:"store_product_offer_id"`
	ObservedAt          time.Time `json:"observed_at"`
	Price               string    `json:"price"`
	PriceKind           string    `json:"price_kind"`
	Source              string    `json:"source"`
	CreatedAt           time.Time `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Brand       sql.NullString `json:"brand"`
	PackageSize sql.NullString `json:"package_size"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ProductIdentifier struct {
	Scheme     string         `json:"scheme"`
	Value      string         `json:"value"`
	ProductID  uuid.UUID      `json:"product_id"`
	Provenance sql.NullString `json:"provenance"`
	Confidence sql.NullString `json:"confidence"`
	CreatedAt  time.Time      `json:"created_at"`
}

type ProductIngredientMapping struct {
	ProductID    uuid.UUID      `json:"product_id"`
	IngredientID uuid.UUID      `json:"ingredient_id"`
	Quantity     sql.NullString `json:"quantity"`
	CreatedAt    time.Time      `json:"created_at"`
}

type RecipeFamily struct {
	ID               uuid.UUID      `json:"id"`
	Slug             string         `json:"slug"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	DefaultVariantID uuid.NullUUID  `json:"default_variant_id"`
	Archived         bool           `json:"archived"`
	CreatedAt        time.Time      `json:"created_at"`
}

type RecipeImportCandidate struct {
	ID                uuid.UUID             `json:"id"`
	SourceID          string                `json:"source_id"`
	SourceUrl         string                `json:"source_url"`
	ExternalID        sql.NullString        `json:"external_id"`
	Title             string                `json:"title"`
	Description       sql.NullString        `json:"description"`
	ImageUrl          sql.NullString        `json:"image_url"`
	Servings          sql.NullInt32         `json:"servings"`
	PrepTimeSec       sql.NullInt32         `json:"prep_time_sec"`
	CookTimeSec       sql.NullInt32         `json:"cook_time_sec"`
	TotalTimeSec      sql.NullInt32         `json:"total_time_sec"`
	Category          sql.NullString        `json:"category"`
	Cuisine           sql.NullString        `json:"cuisine"`
	Attribution       sql.NullString        `json:"attribution"`
	Rating            sql.NullString        `json:"rating"`
	RatingCount       sql.NullInt32         `json:"rating_count"`
	Nutrition         pqtype.NullRawMessage `json:"nutrition"`
	RawJsonld         pqtype.NullRawMessage `json:"raw_jsonld"`
	LicenseNote       sql.NullString        `json:"license_note"`
	ImportedAt        time.Time             `json:"imported_at"`
	FirstServedAt     sql.NullTime          `json:"first_served_at"`
	Status            string                `json:"status"`
	PromotedVariantID uuid.NullUUID         `json:"promoted_variant_id"`
}

type RecipeImportCandidateIngredient struct {
	CandidateID  uuid.UUID      `json:"candidate_id"`
	LineNo       int32          `json:"line_no"`
	RawText      string         `json:"raw_text"`
	IngredientID uuid.NullUUID  `json:"ingredient_id"`
	Quantity     sql.NullString `json:"quantity"`
	Unit         sql.NullString `json:"unit"`
	NeedsReview  bool           `json:"needs_review"`
}

type RecipeIngredient struct {
	RecipeRefID  uuid.UUID      `json:"recipe_ref_id"`
	IngredientID uuid.UUID      `json:"ingredient_id"`
	Quantity     sql.NullString `json:"quantity"`
	Unit         sql.NullString `json:"unit"`
}

type RecipeRef struct {
	ID             uuid.UUID             `json:"id"`
	MealieRecipeID string                `json:"mealie_recipe_id"`
	Title          string                `json:"title"`
	Tags           []string              `json:"tags"`
	Effort         int16                 `json:"effort"`
	LastSyncedAt   time.Time             `json:"last_synced_at"`
	RawSnapshot    pqtype.NullRawMessage `json:"raw_snapshot"`
}

type RecipeRevision struct {
	ID           uuid.UUID       `json:"id"`
	VariantID    uuid.UUID       `json:"variant_id"`
	Servings     sql.NullInt32   `json:"servings"`
	PrepTimeSec  sql.NullInt32   `json:"prep_time_sec"`
	CookTimeSec  sql.NullInt32   `json:"cook_time_sec"`
	TotalTimeSec sql.NullInt32   `json:"total_time_sec"`
	Description  sql.NullString  `json:"description"`
	Ingredients  json.RawMessage `json:"ingredients"`
	Steps        json.RawMessage `json:"steps"`
	CreatedAt    time.Time       `json:"created_at"`
}

type RecipeRevisionParent struct {
	RevisionID       uuid.UUID `json:"revision_id"`
	ParentRevisionID uuid.UUID `json:"parent_revision_id"`
}

type RecipeSourceRef struct {
	ID             uuid.UUID      `json:"id"`
	RecipeFamilyID uuid.UUID      `json:"recipe_family_id"`
	Source         string         `json:"source"`
	SourceRecipeID string         `json:"source_recipe_id"`
	ImportedAt     time.Time      `json:"imported_at"`
	ImportedBy     sql.NullString `json:"imported_by"`
}

type RecipeVariant struct {
	ID                uuid.UUID      `json:"id"`
	Slug              string         `json:"slug"`
	FamilyID          uuid.UUID      `json:"family_id"`
	Title             string         `json:"title"`
	SourceAttribution sql.NullString `json:"source_attribution"`
	Archived          bool           `json:"archived"`
	CreatedAt         time.Time      `json:"created_at"`
}

type Retailer struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type RetailerCredential struct {
	Retailer   string          `json:"retailer"`
	Tier       string          `json:"tier"`
	Payload    json.RawMessage `json:"payload"`
	UploadedAt time.Time       `json:"uploaded_at"`
}

type RetailerListBinding struct {
	ShoppingListID uuid.UUID      `json:"shopping_list_id"`
	Retailer       string         `json:"retailer"`
	ExternalListID string         `json:"external_list_id"`
	SyncDirection  string         `json:"sync_direction"`
	LastPushedAt   sql.NullTime   `json:"last_pushed_at"`
	LastPushStatus sql.NullString `json:"last_push_status"`
}

type RetailerProduct struct {
	ID          uuid.UUID      `json:"id"`
	Slug        string         `json:"slug"`
	RetailerID  uuid.UUID      `json:"retailer_id"`
	ProductID   uuid.NullUUID  `json:"product_id"`
	RetailerSku string         `json:"retailer_sku"`
	DisplayName sql.NullString `json:"display_name"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ShoppingCart struct {
	ID             uuid.UUID `json:"id"`
	ShoppingListID uuid.UUID `json:"shopping_list_id"`
	Retailer       string    `json:"retailer"`
	CreatedAt      time.Time `json:"created_at"`
	Status         string    `json:"status"`
}

type ShoppingCartItem struct {
	ShoppingCartID     uuid.UUID     `json:"shopping_cart_id"`
	LineNo             int32         `json:"line_no"`
	RetailerProductID  string        `json:"retailer_product_id"`
	Quantity           string        `json:"quantity"`
	Unit               string        `json:"unit"`
	ResolvedPriceMinor sql.NullInt64 `json:"resolved_price_minor"`
	Currency           string        `json:"currency"`
}

type ShoppingList struct {
	ID            uuid.UUID     `json:"id"`
	OwnerPersonID uuid.NullUUID `json:"owner_person_id"`
	Name          string        `json:"name"`
	Status        string        `json:"status"`
	CreatedAt     time.Time     `json:"created_at"`
}

type ShoppingListItem struct {
	ID                    uuid.UUID      `json:"id"`
	ShoppingListID        uuid.UUID      `json:"shopping_list_id"`
	ShoppingRequirementID uuid.NullUUID  `json:"shopping_requirement_id"`
	IngredientID          uuid.NullUUID  `json:"ingredient_id"`
	Label                 sql.NullString `json:"label"`
	Quantity              string         `json:"quantity"`
	Unit                  string         `json:"unit"`
	Checked               bool           `json:"checked"`
	AddedAt               time.Time      `json:"added_at"`
	NoteMatchKey          sql.NullString `json:"note_match_key"`
	ResolvedAt            sql.NullTime   `json:"resolved_at"`
}

type ShoppingRequirement struct {
	ID              uuid.UUID      `json:"id"`
	PlanID          uuid.UUID      `json:"plan_id"`
	IngredientID    uuid.UUID      `json:"ingredient_id"`
	Quantity        string         `json:"quantity"`
	Unit            string         `json:"unit"`
	AcceptableForms []string       `json:"acceptable_forms"`
	PreferredForm   sql.NullString `json:"preferred_form"`
}

type Store struct {
	ID         uuid.UUID       `json:"id"`
	Slug       string          `json:"slug"`
	RetailerID uuid.UUID       `json:"retailer_id"`
	Name       string          `json:"name"`
	CreatedAt  time.Time       `json:"created_at"`
	Latitude   sql.NullFloat64 `json:"latitude"`
	Longitude  sql.NullFloat64 `json:"longitude"`
}

type StoreProductOffer struct {
	ID                uuid.UUID `json:"id"`
	StoreID           uuid.UUID `json:"store_id"`
	RetailerProductID uuid.UUID `json:"retailer_product_id"`
	CurrentlyCarried  bool      `json:"currently_carried"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Unit struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Dimension string `json:"dimension"`
}

type UnitConversion struct {
	FromUnit string `json:"from_unit"`
	ToUnit   string `json:"to_unit"`
	Factor   string `json:"factor"`
}
