// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pantry.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createInventoryLocation = `-- name: CreateInventoryLocation :exec
INSERT INTO inventory_location (id, slug, household_id, name, location_type, parent_location_id, archived_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInventoryLocationParams struct {
	ID               uuid.UUID      `json:"id"`
	Slug             string         `json:"slug"`
	HouseholdID      uuid.UUID      `json:"household_id"`
	Name             string         `json:"name"`
	LocationType     sql.NullString `json:"location_type"`
	ParentLocationID uuid.NullUUID  `json:"parent_location_id"`
	ArchivedAt       sql.NullTime   `json:"archived_at"`
}

func (q *Queries) CreateInventoryLocation(ctx context.Context, arg CreateInventoryLocationParams) error {
	_, err := q.db.ExecContext(ctx, createInventoryLocation,
		arg.ID,
		arg.Slug,
		arg.HouseholdID,
		arg.Name,
		arg.LocationType,
		arg.ParentLocationID,
		arg.ArchivedAt,
	)
	return err
}

const getInventoryLocation = `-- name: GetInventoryLocation :one
SELECT id, slug, household_id, name, location_type, parent_location_id, archived_at
FROM inventory_location WHERE id = $1
`

func (q *Queries) GetInventoryLocation(ctx context.Context, id uuid.UUID) (InventoryLocation, error) {
	row := q.db.QueryRowContext(ctx, getInventoryLocation, id)
	var i InventoryLocation
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HouseholdID,
		&i.Name,
		&i.LocationType,
		&i.ParentLocationID,
		&i.ArchivedAt,
	)
	return i, err
}

const getInventoryLot = `-- name: GetInventoryLot :one
SELECT id, ingredient_id, product_id, location_id, quantity, unit, confidence, best_before, opened_at, created_at, updated_at
FROM inventory_lot WHERE id = $1
`

func (q *Queries) GetInventoryLot(ctx context.Context, id uuid.UUID) (InventoryLot, error) {
	row := q.db.QueryRowContext(ctx, getInventoryLot, id)
	var i InventoryLot
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.ProductID,
		&i.LocationID,
		&i.Quantity,
		&i.Unit,
		&i.Confidence,
		&i.BestBefore,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiringLots = `-- name: ListExpiringLots :many
SELECT id, ingredient_id, product_id, location_id, quantity, unit, confidence, best_before, opened_at, created_at, updated_at
FROM inventory_lot
WHERE best_before IS NOT NULL
  AND best_before <= CURRENT_DATE + $1::int
ORDER BY best_before ASC
`

func (q *Queries) ListExpiringLots(ctx context.Context, dollar_1 int32) ([]InventoryLot, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringLots, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryLot
	for rows.Next() {
		var i InventoryLot
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.Unit,
			&i.Confidence,
			&i.BestBefore,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryLocations = `-- name: ListInventoryLocations :many
SELECT id, slug, household_id, name, location_type, parent_location_id, archived_at
FROM inventory_location
WHERE location_type = $1 AND archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListInventoryLocations(ctx context.Context, locationType sql.NullString) ([]InventoryLocation, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryLocations, locationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryLocation
	for rows.Next() {
		var i InventoryLocation
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.HouseholdID,
			&i.Name,
			&i.LocationType,
			&i.ParentLocationID,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotsUnderLocation = `-- name: ListLotsUnderLocation :many
SELECT id, ingredient_id, product_id, location_id, quantity, unit, confidence, best_before, opened_at, created_at, updated_at
FROM inventory_lot
WHERE location_id = $1
ORDER BY best_before ASC NULLS LAST
`

func (q *Queries) ListLotsUnderLocation(ctx context.Context, locationID uuid.UUID) ([]InventoryLot, error) {
	rows, err := q.db.QueryContext(ctx, listLotsUnderLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryLot
	for rows.Next() {
		var i InventoryLot
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.Unit,
			&i.Confidence,
			&i.BestBefore,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPantryIngredientIDs = `-- name: ListPantryIngredientIDs :many
SELECT DISTINCT ingredient_id
FROM inventory_lot
WHERE quantity > 0
ORDER BY ingredient_id
`

func (q *Queries) ListPantryIngredientIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listPantryIngredientIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var ingredient_id uuid.UUID
		if err := rows.Scan(&ingredient_id); err != nil {
			return nil, err
		}
		items = append(items, ingredient_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdjust = `-- name: RecordAdjust :exec
UPDATE inventory_lot
SET quantity = $2,
    updated_at = NOW()
WHERE id = $1
`

type RecordAdjustParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity string    `json:"quantity"`
}

func (q *Queries) RecordAdjust(ctx context.Context, arg RecordAdjustParams) error {
	_, err := q.db.ExecContext(ctx, recordAdjust, arg.ID, arg.Quantity)
	return err
}

const recordConsume = `-- name: RecordConsume :exec
UPDATE inventory_lot
SET quantity = quantity - $2,
    updated_at = NOW()
WHERE id = $1
`

type RecordConsumeParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity string    `json:"quantity"`
}

func (q *Queries) RecordConsume(ctx context.Context, arg RecordConsumeParams) error {
	_, err := q.db.ExecContext(ctx, recordConsume, arg.ID, arg.Quantity)
	return err
}

const recordDiscard = `-- name: RecordDiscard :exec
UPDATE inventory_lot
SET quantity = quantity - $2,
    updated_at = NOW()
WHERE id = $1
`

type RecordDiscardParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity string    `json:"quantity"`
}

func (q *Queries) RecordDiscard(ctx context.Context, arg RecordDiscardParams) error {
	_, err := q.db.ExecContext(ctx, recordDiscard, arg.ID, arg.Quantity)
	return err
}

const recordMarkEmpty = `-- name: RecordMarkEmpty :exec
UPDATE inventory_lot
SET quantity = 0,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RecordMarkEmpty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, recordMarkEmpty, id)
	return err
}

const recordOpen = `-- name: RecordOpen :exec
UPDATE inventory_lot
SET opened_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RecordOpen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, recordOpen, id)
	return err
}
