// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPerson = `-- name: CreatePerson :exec
INSERT INTO person (id, name, weight)
VALUES ($1, $2, $3)
`

type CreatePersonParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Weight string    `json:"weight"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.ExecContext(ctx, createPerson, arg.ID, arg.Name, arg.Weight)
	return err
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, weight FROM person WHERE id = $1
`

type GetPersonRow struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Weight string    `json:"weight"`
}

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (GetPersonRow, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i GetPersonRow
	err := row.Scan(&i.ID, &i.Name, &i.Weight)
	return i, err
}

const listPeople = `-- name: ListPeople :many
SELECT id, name, weight FROM person ORDER BY name
`

type ListPeopleRow struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Weight string    `json:"weight"`
}

func (q *Queries) ListPeople(ctx context.Context) ([]ListPeopleRow, error) {
	rows, err := q.db.QueryContext(ctx, listPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeopleRow
	for rows.Next() {
		var i ListPeopleRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferences = `-- name: ListPreferences :many
SELECT person_id, tag, sentiment, confidence
FROM person_preference
WHERE person_id = $1
ORDER BY tag
`

type ListPreferencesRow struct {
	PersonID   uuid.UUID `json:"person_id"`
	Tag        string    `json:"tag"`
	Sentiment  int16     `json:"sentiment"`
	Confidence string    `json:"confidence"`
}

func (q *Queries) ListPreferences(ctx context.Context, personID uuid.UUID) ([]ListPreferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPreferences, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPreferencesRow
	for rows.Next() {
		var i ListPreferencesRow
		if err := rows.Scan(
			&i.PersonID,
			&i.Tag,
			&i.Sentiment,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordObservation = `-- name: RecordObservation :exec
INSERT INTO preference_observation (person_id, tag, sentiment, observed_at)
VALUES ($1, $2, $3, $4)
`

type RecordObservationParams struct {
	PersonID   uuid.UUID `json:"person_id"`
	Tag        string    `json:"tag"`
	Sentiment  int16     `json:"sentiment"`
	ObservedAt time.Time `json:"observed_at"`
}

func (q *Queries) RecordObservation(ctx context.Context, arg RecordObservationParams) error {
	_, err := q.db.ExecContext(ctx, recordObservation,
		arg.PersonID,
		arg.Tag,
		arg.Sentiment,
		arg.ObservedAt,
	)
	return err
}

const updatePerson = `-- name: UpdatePerson :exec
UPDATE person SET name = $2, weight = $3 WHERE id = $1
`

type UpdatePersonParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Weight string    `json:"weight"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) error {
	_, err := q.db.ExecContext(ctx, updatePerson, arg.ID, arg.Name, arg.Weight)
	return err
}

const upsertPreference = `-- name: UpsertPreference :exec
INSERT INTO person_preference (person_id, tag, sentiment, confidence)
VALUES ($1, $2, $3, $4)
ON CONFLICT (person_id, tag) DO UPDATE
SET sentiment = EXCLUDED.sentiment,
    confidence = EXCLUDED.confidence
`

type UpsertPreferenceParams struct {
	PersonID   uuid.UUID `json:"person_id"`
	Tag        string    `json:"tag"`
	Sentiment  int16     `json:"sentiment"`
	Confidence string    `json:"confidence"`
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPreference,
		arg.PersonID,
		arg.Tag,
		arg.Sentiment,
		arg.Confidence,
	)
	return err
}
