// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planning.sql

package sqlc

import (
	"context"
)

const listEffortProfiles = `-- name: ListEffortProfiles :many
SELECT weekday, kitchen_energy
FROM effort_profile
ORDER BY weekday
`

func (q *Queries) ListEffortProfiles(ctx context.Context) ([]EffortProfile, error) {
	rows, err := q.db.QueryContext(ctx, listEffortProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EffortProfile
	for rows.Next() {
		var i EffortProfile
		if err := rows.Scan(&i.Weekday, &i.KitchenEnergy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
