// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const listAllStores = `-- name: ListAllStores :many
SELECT id, slug, retailer_id, name, created_at
FROM store
ORDER BY retailer_id, name
`

type ListAllStoresRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	RetailerID uuid.UUID `json:"retailer_id"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListAllStores(ctx context.Context) ([]ListAllStoresRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllStoresRow
	for rows.Next() {
		var i ListAllStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.RetailerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentPrices = `-- name: ListCurrentPrices :many
SELECT spo.id, spo.store_id, spo.retailer_product_id, spo.currently_carried,
       rp.display_name AS product_name,
       s.name AS store_name,
       r.name AS retailer_name,
       po.price, po.price_kind, po.observed_at
FROM store_product_offer spo
JOIN retailer_product rp ON spo.retailer_product_id = rp.id
JOIN store s ON spo.store_id = s.id
JOIN retailer r ON s.retailer_id = r.id
LEFT JOIN price_observation po ON po.store_product_offer_id = spo.id
    AND po.observed_at = (SELECT MAX(observed_at) FROM price_observation WHERE store_product_offer_id = spo.id)
WHERE spo.currently_carried
ORDER BY rp.display_name, s.name
`

type ListCurrentPricesRow struct {
	ID                uuid.UUID      `json:"id"`
	StoreID           uuid.UUID      `json:"store_id"`
	RetailerProductID uuid.UUID      `json:"retailer_product_id"`
	CurrentlyCarried  bool           `json:"currently_carried"`
	ProductName       sql.NullString `json:"product_name"`
	StoreName         string         `json:"store_name"`
	RetailerName      string         `json:"retailer_name"`
	Price             sql.NullString `json:"price"`
	PriceKind         sql.NullString `json:"price_kind"`
	ObservedAt        sql.NullTime   `json:"observed_at"`
}

func (q *Queries) ListCurrentPrices(ctx context.Context) ([]ListCurrentPricesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentPricesRow
	for rows.Next() {
		var i ListCurrentPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.RetailerProductID,
			&i.CurrentlyCarried,
			&i.ProductName,
			&i.StoreName,
			&i.RetailerName,
			&i.Price,
			&i.PriceKind,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetailerProducts = `-- name: ListRetailerProducts :many
SELECT id, slug, retailer_id, product_id, retailer_sku, display_name, created_at
FROM retailer_product
WHERE retailer_id = $1
ORDER BY display_name
`

func (q *Queries) ListRetailerProducts(ctx context.Context, retailerID uuid.UUID) ([]RetailerProduct, error) {
	rows, err := q.db.QueryContext(ctx, listRetailerProducts, retailerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetailerProduct
	for rows.Next() {
		var i RetailerProduct
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.RetailerID,
			&i.ProductID,
			&i.RetailerSku,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetailers = `-- name: ListRetailers :many
SELECT id, slug, name, created_at
FROM retailer
ORDER BY name
`

func (q *Queries) ListRetailers(ctx context.Context) ([]Retailer, error) {
	rows, err := q.db.QueryContext(ctx, listRetailers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Retailer
	for rows.Next() {
		var i Retailer
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreProductOffers = `-- name: ListStoreProductOffers :many
SELECT id, store_id, retailer_product_id, currently_carried, created_at, updated_at
FROM store_product_offer
WHERE store_id = $1
ORDER BY retailer_product_id
`

func (q *Queries) ListStoreProductOffers(ctx context.Context, storeID uuid.UUID) ([]StoreProductOffer, error) {
	rows, err := q.db.QueryContext(ctx, listStoreProductOffers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreProductOffer
	for rows.Next() {
		var i StoreProductOffer
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.RetailerProductID,
			&i.CurrentlyCarried,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStores = `-- name: ListStores :many
SELECT id, slug, retailer_id, name, created_at
FROM store
WHERE retailer_id = $1
ORDER BY name
`

type ListStoresRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	RetailerID uuid.UUID `json:"retailer_id"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListStores(ctx context.Context, retailerID uuid.UUID) ([]ListStoresRow, error) {
	rows, err := q.db.QueryContext(ctx, listStores, retailerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoresRow
	for rows.Next() {
		var i ListStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.RetailerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priceObservationsForProduct = `-- name: PriceObservationsForProduct :many
SELECT po.id, po.store_product_offer_id, po.observed_at, po.price, po.price_kind, po.source
FROM price_observation po
JOIN store_product_offer spo ON po.store_product_offer_id = spo.id
WHERE spo.retailer_product_id = $1
ORDER BY po.observed_at DESC
`

type PriceObservationsForProductRow struct {
	ID                  uuid.UUID `json:"id"`
	StoreProductOfferID uuid.UUID `json:"store_product_offer_id"`
	ObservedAt          time.Time `json:"observed_at"`
	Price               string    `json:"price"`
	PriceKind           string    `json:"price_kind"`
	Source              string    `json:"source"`
}

func (q *Queries) PriceObservationsForProduct(ctx context.Context, retailerProductID uuid.UUID) ([]PriceObservationsForProductRow, error) {
	rows, err := q.db.QueryContext(ctx, priceObservationsForProduct, retailerProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceObservationsForProductRow
	for rows.Next() {
		var i PriceObservationsForProductRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreProductOfferID,
			&i.ObservedAt,
			&i.Price,
			&i.PriceKind,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priceObservationsForStore = `-- name: PriceObservationsForStore :many
SELECT po.id, po.store_product_offer_id, po.observed_at, po.price, po.price_kind, po.source
FROM price_observation po
WHERE po.store_product_offer_id IN (
    SELECT id FROM store_product_offer WHERE store_id = $1
)
ORDER BY po.observed_at DESC
`

type PriceObservationsForStoreRow struct {
	ID                  uuid.UUID `json:"id"`
	StoreProductOfferID uuid.UUID `json:"store_product_offer_id"`
	ObservedAt          time.Time `json:"observed_at"`
	Price               string    `json:"price"`
	PriceKind           string    `json:"price_kind"`
	Source              string    `json:"source"`
}

func (q *Queries) PriceObservationsForStore(ctx context.Context, storeID uuid.UUID) ([]PriceObservationsForStoreRow, error) {
	rows, err := q.db.QueryContext(ctx, priceObservationsForStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceObservationsForStoreRow
	for rows.Next() {
		var i PriceObservationsForStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreProductOfferID,
			&i.ObservedAt,
			&i.Price,
			&i.PriceKind,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
