// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddMealReaction(ctx context.Context, arg AddMealReactionParams) error
	AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) error
	AddRecipeRevisionParent(ctx context.Context, arg AddRecipeRevisionParentParams) error
	CreateInventoryLocation(ctx context.Context, arg CreateInventoryLocationParams) error
	CreateMealEvent(ctx context.Context, arg CreateMealEventParams) (uuid.UUID, error)
	CreateOrUpdateRetailerListBinding(ctx context.Context, arg CreateOrUpdateRetailerListBindingParams) error
	CreatePerson(ctx context.Context, arg CreatePersonParams) error
	CreateRecipeFamily(ctx context.Context, arg CreateRecipeFamilyParams) error
	CreateRecipeRevision(ctx context.Context, arg CreateRecipeRevisionParams) (uuid.UUID, error)
	CreateRecipeVariant(ctx context.Context, arg CreateRecipeVariantParams) error
	CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (uuid.UUID, error)
	CreateShoppingListItem(ctx context.Context, arg CreateShoppingListItemParams) error
	DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) error
	DeleteIngredientAlias(ctx context.Context, arg DeleteIngredientAliasParams) error
	GetExternalRecipeSource(ctx context.Context, id string) (ExternalRecipeSource, error)
	GetImportCandidate(ctx context.Context, id uuid.UUID) (GetImportCandidateRow, error)
	GetIngredientAlias(ctx context.Context, arg GetIngredientAliasParams) (IngredientAlias, error)
	GetIngredientMapping(ctx context.Context, arg GetIngredientMappingParams) (IngredientExternalRef, error)
	GetInventoryLocation(ctx context.Context, id uuid.UUID) (InventoryLocation, error)
	GetInventoryLot(ctx context.Context, id uuid.UUID) (InventoryLot, error)
	GetMealEvent(ctx context.Context, id uuid.UUID) (GetMealEventRow, error)
	GetMealPlan(ctx context.Context, id uuid.UUID) (MealPlan, error)
	GetOrCreateMealPlan(ctx context.Context, arg GetOrCreateMealPlanParams) (MealPlan, error)
	GetPerson(ctx context.Context, id uuid.UUID) (GetPersonRow, error)
	GetRecipeFamily(ctx context.Context, id uuid.UUID) (RecipeFamily, error)
	GetRecipeFamilyBySlug(ctx context.Context, slug string) (RecipeFamily, error)
	GetRecipeRating(ctx context.Context, recipeRefID uuid.UUID) (GetRecipeRatingRow, error)
	GetRecipeRef(ctx context.Context, id uuid.UUID) (RecipeRef, error)
	GetRecipeRefByMealieID(ctx context.Context, mealieRecipeID string) (RecipeRef, error)
	GetRecipeRevision(ctx context.Context, id uuid.UUID) (GetRecipeRevisionRow, error)
	GetRecipeSourceRefByFamily(ctx context.Context, recipeFamilyID uuid.UUID) (RecipeSourceRef, error)
	GetRecipeSourceRefBySource(ctx context.Context, arg GetRecipeSourceRefBySourceParams) (RecipeSourceRef, error)
	GetRecipeVariant(ctx context.Context, id uuid.UUID) (RecipeVariant, error)
	InsertCandidate(ctx context.Context, arg InsertCandidateParams) error
	InsertShoppingRequirement(ctx context.Context, arg InsertShoppingRequirementParams) error
	ListAllRecipeIngredients(ctx context.Context) ([]RecipeIngredient, error)
	ListAllStores(ctx context.Context) ([]ListAllStoresRow, error)
	ListCandidateIngredients(ctx context.Context, candidateID uuid.UUID) ([]RecipeImportCandidateIngredient, error)
	ListCandidates(ctx context.Context, planID uuid.UUID) ([]ListCandidatesRow, error)
	ListCurrentPrices(ctx context.Context) ([]ListCurrentPricesRow, error)
	ListDecisions(ctx context.Context, planID uuid.UUID) ([]ListDecisionsRow, error)
	ListEffortProfiles(ctx context.Context) ([]EffortProfile, error)
	ListExpiringLots(ctx context.Context, dollar_1 int32) ([]InventoryLot, error)
	ListFavoritesForRecipe(ctx context.Context, recipeRefID uuid.UUID) ([]Favorite, error)
	ListImportCandidates(ctx context.Context, dollar_1 string) ([]ListImportCandidatesRow, error)
	ListIngredientAliases(ctx context.Context, householdID uuid.NullUUID) ([]IngredientAlias, error)
	ListInventoryLocations(ctx context.Context, locationType sql.NullString) ([]InventoryLocation, error)
	ListLotsUnderLocation(ctx context.Context, locationID uuid.UUID) ([]InventoryLot, error)
	ListMealEvents(ctx context.Context, recipeRefID uuid.UUID) ([]ListMealEventsRow, error)
	ListMealPlans(ctx context.Context) ([]MealPlan, error)
	ListMealReactions(ctx context.Context, mealEventID uuid.UUID) ([]ListMealReactionsRow, error)
	ListPantryIngredientIDs(ctx context.Context) ([]uuid.UUID, error)
	ListPeople(ctx context.Context) ([]ListPeopleRow, error)
	ListPreferences(ctx context.Context, personID uuid.UUID) ([]ListPreferencesRow, error)
	ListRecipeFamilies(ctx context.Context) ([]RecipeFamily, error)
	ListRecipeIngredients(ctx context.Context, recipeRefID uuid.UUID) ([]RecipeIngredient, error)
	ListRecipeRefs(ctx context.Context) ([]RecipeRef, error)
	ListRecipeRevisionParents(ctx context.Context, revisionID uuid.UUID) ([]uuid.UUID, error)
	ListRecipeRevisions(ctx context.Context, variantID uuid.UUID) ([]ListRecipeRevisionsRow, error)
	ListRecipeVariants(ctx context.Context, familyID uuid.UUID) ([]RecipeVariant, error)
	ListRetailerProducts(ctx context.Context, retailerID uuid.UUID) ([]RetailerProduct, error)
	ListRetailers(ctx context.Context) ([]Retailer, error)
	ListShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) ([]ListShoppingListItemsRow, error)
	ListShoppingLists(ctx context.Context) ([]ShoppingList, error)
	ListShoppingRequirements(ctx context.Context, planID uuid.UUID) ([]ListShoppingRequirementsRow, error)
	ListStoreProductOffers(ctx context.Context, storeID uuid.UUID) ([]StoreProductOffer, error)
	ListStores(ctx context.Context, retailerID uuid.UUID) ([]ListStoresRow, error)
	ListUnmappedMealieRecipes(ctx context.Context) ([]string, error)
	PriceObservationsForProduct(ctx context.Context, retailerProductID uuid.UUID) ([]PriceObservationsForProductRow, error)
	PriceObservationsForStore(ctx context.Context, storeID uuid.UUID) ([]PriceObservationsForStoreRow, error)
	RecordAdjust(ctx context.Context, arg RecordAdjustParams) error
	RecordConsume(ctx context.Context, arg RecordConsumeParams) error
	RecordDiscard(ctx context.Context, arg RecordDiscardParams) error
	RecordMarkEmpty(ctx context.Context, id uuid.UUID) error
	RecordObservation(ctx context.Context, arg RecordObservationParams) error
	RecordOpen(ctx context.Context, id uuid.UUID) error
	ResolveIngredientAlias(ctx context.Context, arg ResolveIngredientAliasParams) (uuid.UUID, error)
	SaveCandidateIngredient(ctx context.Context, arg SaveCandidateIngredientParams) error
	SaveImportCandidate(ctx context.Context, arg SaveImportCandidateParams) (uuid.UUID, error)
	SetCandidatePromoted(ctx context.Context, arg SetCandidatePromotedParams) error
	SetCandidateStatus(ctx context.Context, arg SetCandidateStatusParams) error
	SetDecision(ctx context.Context, arg SetDecisionParams) error
	SetMealPlanStatus(ctx context.Context, arg SetMealPlanStatusParams) error
	SetRecipeFamilyDefaultVariant(ctx context.Context, arg SetRecipeFamilyDefaultVariantParams) error
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) error
	UpsertExternalRecipeSource(ctx context.Context, arg UpsertExternalRecipeSourceParams) error
	UpsertFavorite(ctx context.Context, arg UpsertFavoriteParams) error
	UpsertIngredient(ctx context.Context, arg UpsertIngredientParams) error
	UpsertIngredientAlias(ctx context.Context, arg UpsertIngredientAliasParams) error
	UpsertIngredientMapping(ctx context.Context, arg UpsertIngredientMappingParams) error
	UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) error
	UpsertRecipeRef(ctx context.Context, arg UpsertRecipeRefParams) error
	UpsertRecipeSourceRef(ctx context.Context, arg UpsertRecipeSourceRefParams) error
}

var _ Querier = (*Queries)(nil)
