// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_family.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addRecipeRevisionParent = `-- name: AddRecipeRevisionParent :exec
INSERT INTO recipe_revision_parent (revision_id, parent_revision_id)
VALUES ($1, $2)
ON CONFLICT (revision_id, parent_revision_id) DO NOTHING
`

type AddRecipeRevisionParentParams struct {
	RevisionID       uuid.UUID `json:"revision_id"`
	ParentRevisionID uuid.UUID `json:"parent_revision_id"`
}

func (q *Queries) AddRecipeRevisionParent(ctx context.Context, arg AddRecipeRevisionParentParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeRevisionParent, arg.RevisionID, arg.ParentRevisionID)
	return err
}

const createRecipeFamily = `-- name: CreateRecipeFamily :exec
INSERT INTO recipe_family (id, slug, name, description, default_variant_id, archived, created_at)
VALUES ($1, $2, $3, $4, $5, false, $6)
`

type CreateRecipeFamilyParams struct {
	ID               uuid.UUID      `json:"id"`
	Slug             string         `json:"slug"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	DefaultVariantID uuid.NullUUID  `json:"default_variant_id"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) CreateRecipeFamily(ctx context.Context, arg CreateRecipeFamilyParams) error {
	_, err := q.db.ExecContext(ctx, createRecipeFamily,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DefaultVariantID,
		arg.CreatedAt,
	)
	return err
}

const createRecipeRevision = `-- name: CreateRecipeRevision :one
INSERT INTO recipe_revision (id, variant_id, servings, description, ingredients, steps, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateRecipeRevisionParams struct {
	ID          uuid.UUID       `json:"id"`
	VariantID   uuid.UUID       `json:"variant_id"`
	Servings    sql.NullInt32   `json:"servings"`
	Description sql.NullString  `json:"description"`
	Ingredients json.RawMessage `json:"ingredients"`
	Steps       json.RawMessage `json:"steps"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) CreateRecipeRevision(ctx context.Context, arg CreateRecipeRevisionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createRecipeRevision,
		arg.ID,
		arg.VariantID,
		arg.Servings,
		arg.Description,
		arg.Ingredients,
		arg.Steps,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createRecipeVariant = `-- name: CreateRecipeVariant :exec
INSERT INTO recipe_variant (id, slug, family_id, title, source_attribution, archived, created_at)
VALUES ($1, $2, $3, $4, $5, false, $6)
`

type CreateRecipeVariantParams struct {
	ID                uuid.UUID      `json:"id"`
	Slug              string         `json:"slug"`
	FamilyID          uuid.UUID      `json:"family_id"`
	Title             string         `json:"title"`
	SourceAttribution sql.NullString `json:"source_attribution"`
	CreatedAt         time.Time      `json:"created_at"`
}

func (q *Queries) CreateRecipeVariant(ctx context.Context, arg CreateRecipeVariantParams) error {
	_, err := q.db.ExecContext(ctx, createRecipeVariant,
		arg.ID,
		arg.Slug,
		arg.FamilyID,
		arg.Title,
		arg.SourceAttribution,
		arg.CreatedAt,
	)
	return err
}

const getRecipeFamily = `-- name: GetRecipeFamily :one
SELECT id, slug, name, description, default_variant_id, archived, created_at
FROM recipe_family WHERE id = $1
`

func (q *Queries) GetRecipeFamily(ctx context.Context, id uuid.UUID) (RecipeFamily, error) {
	row := q.db.QueryRowContext(ctx, getRecipeFamily, id)
	var i RecipeFamily
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DefaultVariantID,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipeFamilyBySlug = `-- name: GetRecipeFamilyBySlug :one
SELECT id, slug, name, description, default_variant_id, archived, created_at
FROM recipe_family WHERE slug = $1
`

func (q *Queries) GetRecipeFamilyBySlug(ctx context.Context, slug string) (RecipeFamily, error) {
	row := q.db.QueryRowContext(ctx, getRecipeFamilyBySlug, slug)
	var i RecipeFamily
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DefaultVariantID,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipeRevision = `-- name: GetRecipeRevision :one
SELECT id, variant_id, servings, description, ingredients, steps, created_at
FROM recipe_revision WHERE id = $1
`

type GetRecipeRevisionRow struct {
	ID          uuid.UUID       `json:"id"`
	VariantID   uuid.UUID       `json:"variant_id"`
	Servings    sql.NullInt32   `json:"servings"`
	Description sql.NullString  `json:"description"`
	Ingredients json.RawMessage `json:"ingredients"`
	Steps       json.RawMessage `json:"steps"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) GetRecipeRevision(ctx context.Context, id uuid.UUID) (GetRecipeRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeRevision, id)
	var i GetRecipeRevisionRow
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Servings,
		&i.Description,
		&i.Ingredients,
		&i.Steps,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipeVariant = `-- name: GetRecipeVariant :one
SELECT id, slug, family_id, title, source_attribution, archived, created_at
FROM recipe_variant WHERE id = $1
`

func (q *Queries) GetRecipeVariant(ctx context.Context, id uuid.UUID) (RecipeVariant, error) {
	row := q.db.QueryRowContext(ctx, getRecipeVariant, id)
	var i RecipeVariant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.FamilyID,
		&i.Title,
		&i.SourceAttribution,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listRecipeFamilies = `-- name: ListRecipeFamilies :many
SELECT id, slug, name, description, default_variant_id, archived, created_at
FROM recipe_family
ORDER BY slug
`

func (q *Queries) ListRecipeFamilies(ctx context.Context) ([]RecipeFamily, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeFamily
	for rows.Next() {
		var i RecipeFamily
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.DefaultVariantID,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRevisionParents = `-- name: ListRecipeRevisionParents :many
SELECT parent_revision_id
FROM recipe_revision_parent
WHERE revision_id = $1
ORDER BY parent_revision_id
`

func (q *Queries) ListRecipeRevisionParents(ctx context.Context, revisionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeRevisionParents, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var parent_revision_id uuid.UUID
		if err := rows.Scan(&parent_revision_id); err != nil {
			return nil, err
		}
		items = append(items, parent_revision_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRevisions = `-- name: ListRecipeRevisions :many
SELECT id, variant_id, servings, description, ingredients, steps, created_at
FROM recipe_revision
WHERE variant_id = $1
ORDER BY created_at DESC
`

type ListRecipeRevisionsRow struct {
	ID          uuid.UUID       `json:"id"`
	VariantID   uuid.UUID       `json:"variant_id"`
	Servings    sql.NullInt32   `json:"servings"`
	Description sql.NullString  `json:"description"`
	Ingredients json.RawMessage `json:"ingredients"`
	Steps       json.RawMessage `json:"steps"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) ListRecipeRevisions(ctx context.Context, variantID uuid.UUID) ([]ListRecipeRevisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeRevisions, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeRevisionsRow
	for rows.Next() {
		var i ListRecipeRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Servings,
			&i.Description,
			&i.Ingredients,
			&i.Steps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeVariants = `-- name: ListRecipeVariants :many
SELECT id, slug, family_id, title, source_attribution, archived, created_at
FROM recipe_variant
WHERE family_id = $1
ORDER BY slug
`

func (q *Queries) ListRecipeVariants(ctx context.Context, familyID uuid.UUID) ([]RecipeVariant, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeVariants, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeVariant
	for rows.Next() {
		var i RecipeVariant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.FamilyID,
			&i.Title,
			&i.SourceAttribution,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecipeFamilyDefaultVariant = `-- name: SetRecipeFamilyDefaultVariant :exec
UPDATE recipe_family SET default_variant_id = $2 WHERE id = $1
`

type SetRecipeFamilyDefaultVariantParams struct {
	ID               uuid.UUID     `json:"id"`
	DefaultVariantID uuid.NullUUID `json:"default_variant_id"`
}

func (q *Queries) SetRecipeFamilyDefaultVariant(ctx context.Context, arg SetRecipeFamilyDefaultVariantParams) error {
	_, err := q.db.ExecContext(ctx, setRecipeFamilyDefaultVariant, arg.ID, arg.DefaultVariantID)
	return err
}
