// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addRecipeIngredient = `-- name: AddRecipeIngredient :exec
INSERT INTO recipe_ingredient (recipe_ref_id, ingredient_id, quantity, unit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (recipe_ref_id, ingredient_id) DO UPDATE
SET quantity = EXCLUDED.quantity,
    unit = EXCLUDED.unit
`

type AddRecipeIngredientParams struct {
	RecipeRefID  uuid.UUID      `json:"recipe_ref_id"`
	IngredientID uuid.UUID      `json:"ingredient_id"`
	Quantity     sql.NullString `json:"quantity"`
	Unit         sql.NullString `json:"unit"`
}

func (q *Queries) AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeIngredient,
		arg.RecipeRefID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
	)
	return err
}

const getIngredientMapping = `-- name: GetIngredientMapping :one
SELECT provider, external_id, ingredient_id, grams_per_unit, default_form, needs_review, updated_at
FROM ingredient_external_ref
WHERE provider = $1 AND external_id = $2
`

type GetIngredientMappingParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetIngredientMapping(ctx context.Context, arg GetIngredientMappingParams) (IngredientExternalRef, error) {
	row := q.db.QueryRowContext(ctx, getIngredientMapping, arg.Provider, arg.ExternalID)
	var i IngredientExternalRef
	err := row.Scan(
		&i.Provider,
		&i.ExternalID,
		&i.IngredientID,
		&i.GramsPerUnit,
		&i.DefaultForm,
		&i.NeedsReview,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeRef = `-- name: GetRecipeRef :one
SELECT id, mealie_recipe_id, title, tags, effort, last_synced_at, raw_snapshot
FROM recipe_ref WHERE id = $1
`

func (q *Queries) GetRecipeRef(ctx context.Context, id uuid.UUID) (RecipeRef, error) {
	row := q.db.QueryRowContext(ctx, getRecipeRef, id)
	var i RecipeRef
	err := row.Scan(
		&i.ID,
		&i.MealieRecipeID,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Effort,
		&i.LastSyncedAt,
		&i.RawSnapshot,
	)
	return i, err
}

const getRecipeRefByMealieID = `-- name: GetRecipeRefByMealieID :one
SELECT id, mealie_recipe_id, title, tags, effort, last_synced_at, raw_snapshot
FROM recipe_ref WHERE mealie_recipe_id = $1
`

func (q *Queries) GetRecipeRefByMealieID(ctx context.Context, mealieRecipeID string) (RecipeRef, error) {
	row := q.db.QueryRowContext(ctx, getRecipeRefByMealieID, mealieRecipeID)
	var i RecipeRef
	err := row.Scan(
		&i.ID,
		&i.MealieRecipeID,
		&i.Title,
		pq.Array(&i.Tags),
		&i.Effort,
		&i.LastSyncedAt,
		&i.RawSnapshot,
	)
	return i, err
}

const listAllRecipeIngredients = `-- name: ListAllRecipeIngredients :many
SELECT recipe_ref_id, ingredient_id, quantity, unit
FROM recipe_ingredient
ORDER BY recipe_ref_id, ingredient_id
`

func (q *Queries) ListAllRecipeIngredients(ctx context.Context) ([]RecipeIngredient, error) {
	rows, err := q.db.QueryContext(ctx, listAllRecipeIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeIngredient
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.RecipeRefID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT recipe_ref_id, ingredient_id, quantity, unit
FROM recipe_ingredient
WHERE recipe_ref_id = $1
ORDER BY ingredient_id
`

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeRefID uuid.UUID) ([]RecipeIngredient, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeIngredients, recipeRefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeIngredient
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.RecipeRefID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRefs = `-- name: ListRecipeRefs :many
SELECT id, mealie_recipe_id, title, tags, effort, last_synced_at, raw_snapshot
FROM recipe_ref
ORDER BY mealie_recipe_id
`

func (q *Queries) ListRecipeRefs(ctx context.Context) ([]RecipeRef, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeRef
	for rows.Next() {
		var i RecipeRef
		if err := rows.Scan(
			&i.ID,
			&i.MealieRecipeID,
			&i.Title,
			pq.Array(&i.Tags),
			&i.Effort,
			&i.LastSyncedAt,
			&i.RawSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngredient = `-- name: UpsertIngredient :exec
INSERT INTO ingredient (id, slug, display)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET slug = EXCLUDED.slug,
    display = EXCLUDED.display
`

type UpsertIngredientParams struct {
	ID      uuid.UUID `json:"id"`
	Slug    string    `json:"slug"`
	Display string    `json:"display"`
}

func (q *Queries) UpsertIngredient(ctx context.Context, arg UpsertIngredientParams) error {
	_, err := q.db.ExecContext(ctx, upsertIngredient, arg.ID, arg.Slug, arg.Display)
	return err
}

const upsertIngredientMapping = `-- name: UpsertIngredientMapping :exec
INSERT INTO ingredient_external_ref (provider, external_id, ingredient_id, grams_per_unit, default_form, needs_review, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider, external_id) DO UPDATE
SET ingredient_id = EXCLUDED.ingredient_id,
    grams_per_unit = EXCLUDED.grams_per_unit,
    default_form = EXCLUDED.default_form,
    needs_review = EXCLUDED.needs_review,
    updated_at = EXCLUDED.updated_at
`

type UpsertIngredientMappingParams struct {
	Provider     string         `json:"provider"`
	ExternalID   string         `json:"external_id"`
	IngredientID uuid.UUID      `json:"ingredient_id"`
	GramsPerUnit sql.NullString `json:"grams_per_unit"`
	DefaultForm  sql.NullString `json:"default_form"`
	NeedsReview  bool           `json:"needs_review"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertIngredientMapping(ctx context.Context, arg UpsertIngredientMappingParams) error {
	_, err := q.db.ExecContext(ctx, upsertIngredientMapping,
		arg.Provider,
		arg.ExternalID,
		arg.IngredientID,
		arg.GramsPerUnit,
		arg.DefaultForm,
		arg.NeedsReview,
		arg.UpdatedAt,
	)
	return err
}

const upsertRecipeRef = `-- name: UpsertRecipeRef :exec
INSERT INTO recipe_ref (id, mealie_recipe_id, title, tags, effort, last_synced_at, raw_snapshot)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (mealie_recipe_id) DO UPDATE
SET title = EXCLUDED.title,
    tags = EXCLUDED.tags,
    effort = EXCLUDED.effort,
    last_synced_at = EXCLUDED.last_synced_at,
    raw_snapshot = EXCLUDED.raw_snapshot
`

type UpsertRecipeRefParams struct {
	ID             uuid.UUID             `json:"id"`
	MealieRecipeID string                `json:"mealie_recipe_id"`
	Title          string                `json:"title"`
	Tags           []string              `json:"tags"`
	Effort         int16                 `json:"effort"`
	LastSyncedAt   time.Time             `json:"last_synced_at"`
	RawSnapshot    pqtype.NullRawMessage `json:"raw_snapshot"`
}

func (q *Queries) UpsertRecipeRef(ctx context.Context, arg UpsertRecipeRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecipeRef,
		arg.ID,
		arg.MealieRecipeID,
		arg.Title,
		pq.Array(arg.Tags),
		arg.Effort,
		arg.LastSyncedAt,
		arg.RawSnapshot,
	)
	return err
}
