// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_source_ref.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getRecipeSourceRefByFamily = `-- name: GetRecipeSourceRefByFamily :one
SELECT id, recipe_family_id, source, source_recipe_id, imported_at, imported_by
FROM recipe_source_ref
WHERE recipe_family_id = $1
`

func (q *Queries) GetRecipeSourceRefByFamily(ctx context.Context, recipeFamilyID uuid.UUID) (RecipeSourceRef, error) {
	row := q.db.QueryRowContext(ctx, getRecipeSourceRefByFamily, recipeFamilyID)
	var i RecipeSourceRef
	err := row.Scan(
		&i.ID,
		&i.RecipeFamilyID,
		&i.Source,
		&i.SourceRecipeID,
		&i.ImportedAt,
		&i.ImportedBy,
	)
	return i, err
}

const getRecipeSourceRefBySource = `-- name: GetRecipeSourceRefBySource :one
SELECT id, recipe_family_id, source, source_recipe_id, imported_at, imported_by
FROM recipe_source_ref
WHERE source = $1 AND source_recipe_id = $2
`

type GetRecipeSourceRefBySourceParams struct {
	Source         string `json:"source"`
	SourceRecipeID string `json:"source_recipe_id"`
}

func (q *Queries) GetRecipeSourceRefBySource(ctx context.Context, arg GetRecipeSourceRefBySourceParams) (RecipeSourceRef, error) {
	row := q.db.QueryRowContext(ctx, getRecipeSourceRefBySource, arg.Source, arg.SourceRecipeID)
	var i RecipeSourceRef
	err := row.Scan(
		&i.ID,
		&i.RecipeFamilyID,
		&i.Source,
		&i.SourceRecipeID,
		&i.ImportedAt,
		&i.ImportedBy,
	)
	return i, err
}

const listUnmappedMealieRecipes = `-- name: ListUnmappedMealieRecipes :many
SELECT rr.mealie_recipe_id
FROM recipe_ref rr
WHERE NOT EXISTS (
    SELECT 1 FROM recipe_source_ref rsr
    WHERE rsr.source = 'mealie' AND rsr.source_recipe_id = rr.mealie_recipe_id
)
ORDER BY rr.mealie_recipe_id
`

func (q *Queries) ListUnmappedMealieRecipes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnmappedMealieRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mealie_recipe_id string
		if err := rows.Scan(&mealie_recipe_id); err != nil {
			return nil, err
		}
		items = append(items, mealie_recipe_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecipeSourceRef = `-- name: UpsertRecipeSourceRef :exec
INSERT INTO recipe_source_ref (id, recipe_family_id, source, source_recipe_id, imported_at, imported_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (source, source_recipe_id) DO UPDATE
SET recipe_family_id = EXCLUDED.recipe_family_id,
    imported_by = EXCLUDED.imported_by
`

type UpsertRecipeSourceRefParams struct {
	ID             uuid.UUID      `json:"id"`
	RecipeFamilyID uuid.UUID      `json:"recipe_family_id"`
	Source         string         `json:"source"`
	SourceRecipeID string         `json:"source_recipe_id"`
	ImportedAt     time.Time      `json:"imported_at"`
	ImportedBy     sql.NullString `json:"imported_by"`
}

func (q *Queries) UpsertRecipeSourceRef(ctx context.Context, arg UpsertRecipeSourceRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecipeSourceRef,
		arg.ID,
		arg.RecipeFamilyID,
		arg.Source,
		arg.SourceRecipeID,
		arg.ImportedAt,
		arg.ImportedBy,
	)
	return err
}
