// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_discovery.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getExternalRecipeSource = `-- name: GetExternalRecipeSource :one
SELECT id, name, kind, base_url, license_note, decision, enabled, created_at
FROM external_recipe_source WHERE id = $1
`

func (q *Queries) GetExternalRecipeSource(ctx context.Context, id string) (ExternalRecipeSource, error) {
	row := q.db.QueryRowContext(ctx, getExternalRecipeSource, id)
	var i ExternalRecipeSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.LicenseNote,
		&i.Decision,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getImportCandidate = `-- name: GetImportCandidate :one
SELECT id, source_id, source_url, external_id, title, description, image_url,
    servings, prep_time_sec, cook_time_sec, total_time_sec, category, cuisine, attribution,
    rating, rating_count, license_note, imported_at, status, promoted_variant_id
FROM recipe_import_candidate WHERE id = $1
`

type GetImportCandidateRow struct {
	ID                uuid.UUID      `json:"id"`
	SourceID          string         `json:"source_id"`
	SourceUrl         string         `json:"source_url"`
	ExternalID        sql.NullString `json:"external_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	ImageUrl          sql.NullString `json:"image_url"`
	Servings          sql.NullInt32  `json:"servings"`
	PrepTimeSec       sql.NullInt32  `json:"prep_time_sec"`
	CookTimeSec       sql.NullInt32  `json:"cook_time_sec"`
	TotalTimeSec      sql.NullInt32  `json:"total_time_sec"`
	Category          sql.NullString `json:"category"`
	Cuisine           sql.NullString `json:"cuisine"`
	Attribution       sql.NullString `json:"attribution"`
	Rating            sql.NullString `json:"rating"`
	RatingCount       sql.NullInt32  `json:"rating_count"`
	LicenseNote       sql.NullString `json:"license_note"`
	ImportedAt        time.Time      `json:"imported_at"`
	Status            string         `json:"status"`
	PromotedVariantID uuid.NullUUID  `json:"promoted_variant_id"`
}

func (q *Queries) GetImportCandidate(ctx context.Context, id uuid.UUID) (GetImportCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, getImportCandidate, id)
	var i GetImportCandidateRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceUrl,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Servings,
		&i.PrepTimeSec,
		&i.CookTimeSec,
		&i.TotalTimeSec,
		&i.Category,
		&i.Cuisine,
		&i.Attribution,
		&i.Rating,
		&i.RatingCount,
		&i.LicenseNote,
		&i.ImportedAt,
		&i.Status,
		&i.PromotedVariantID,
	)
	return i, err
}

const listCandidateIngredients = `-- name: ListCandidateIngredients :many
SELECT candidate_id, line_no, raw_text, ingredient_id, quantity, unit, needs_review
FROM recipe_import_candidate_ingredient
WHERE candidate_id = $1
ORDER BY line_no
`

func (q *Queries) ListCandidateIngredients(ctx context.Context, candidateID uuid.UUID) ([]RecipeImportCandidateIngredient, error) {
	rows, err := q.db.QueryContext(ctx, listCandidateIngredients, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeImportCandidateIngredient
	for rows.Next() {
		var i RecipeImportCandidateIngredient
		if err := rows.Scan(
			&i.CandidateID,
			&i.LineNo,
			&i.RawText,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.NeedsReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportCandidates = `-- name: ListImportCandidates :many
SELECT id, source_id, source_url, external_id, title, description, image_url,
    servings, prep_time_sec, cook_time_sec, total_time_sec, category, cuisine, attribution,
    rating, rating_count, license_note, imported_at, status, promoted_variant_id
FROM recipe_import_candidate
WHERE ($1::text IS NULL OR status = $1)
ORDER BY imported_at DESC
`

type ListImportCandidatesRow struct {
	ID                uuid.UUID      `json:"id"`
	SourceID          string         `json:"source_id"`
	SourceUrl         string         `json:"source_url"`
	ExternalID        sql.NullString `json:"external_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	ImageUrl          sql.NullString `json:"image_url"`
	Servings          sql.NullInt32  `json:"servings"`
	PrepTimeSec       sql.NullInt32  `json:"prep_time_sec"`
	CookTimeSec       sql.NullInt32  `json:"cook_time_sec"`
	TotalTimeSec      sql.NullInt32  `json:"total_time_sec"`
	Category          sql.NullString `json:"category"`
	Cuisine           sql.NullString `json:"cuisine"`
	Attribution       sql.NullString `json:"attribution"`
	Rating            sql.NullString `json:"rating"`
	RatingCount       sql.NullInt32  `json:"rating_count"`
	LicenseNote       sql.NullString `json:"license_note"`
	ImportedAt        time.Time      `json:"imported_at"`
	Status            string         `json:"status"`
	PromotedVariantID uuid.NullUUID  `json:"promoted_variant_id"`
}

func (q *Queries) ListImportCandidates(ctx context.Context, dollar_1 string) ([]ListImportCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listImportCandidates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportCandidatesRow
	for rows.Next() {
		var i ListImportCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.SourceUrl,
			&i.ExternalID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Servings,
			&i.PrepTimeSec,
			&i.CookTimeSec,
			&i.TotalTimeSec,
			&i.Category,
			&i.Cuisine,
			&i.Attribution,
			&i.Rating,
			&i.RatingCount,
			&i.LicenseNote,
			&i.ImportedAt,
			&i.Status,
			&i.PromotedVariantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCandidateIngredient = `-- name: SaveCandidateIngredient :exec
INSERT INTO recipe_import_candidate_ingredient (candidate_id, line_no, raw_text, ingredient_id, quantity, unit, needs_review)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (candidate_id, line_no) DO UPDATE
SET raw_text = EXCLUDED.raw_text,
    ingredient_id = EXCLUDED.ingredient_id,
    quantity = EXCLUDED.quantity,
    unit = EXCLUDED.unit,
    needs_review = EXCLUDED.needs_review
`

type SaveCandidateIngredientParams struct {
	CandidateID  uuid.UUID      `json:"candidate_id"`
	LineNo       int32          `json:"line_no"`
	RawText      string         `json:"raw_text"`
	IngredientID uuid.NullUUID  `json:"ingredient_id"`
	Quantity     sql.NullString `json:"quantity"`
	Unit         sql.NullString `json:"unit"`
	NeedsReview  bool           `json:"needs_review"`
}

func (q *Queries) SaveCandidateIngredient(ctx context.Context, arg SaveCandidateIngredientParams) error {
	_, err := q.db.ExecContext(ctx, saveCandidateIngredient,
		arg.CandidateID,
		arg.LineNo,
		arg.RawText,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
		arg.NeedsReview,
	)
	return err
}

const saveImportCandidate = `-- name: SaveImportCandidate :one
INSERT INTO recipe_import_candidate (id, source_id, source_url, external_id, title, description, image_url,
    servings, prep_time_sec, cook_time_sec, total_time_sec, category, cuisine, attribution,
    rating, rating_count, license_note, imported_at, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id
`

type SaveImportCandidateParams struct {
	ID           uuid.UUID      `json:"id"`
	SourceID     string         `json:"source_id"`
	SourceUrl    string         `json:"source_url"`
	ExternalID   sql.NullString `json:"external_id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	ImageUrl     sql.NullString `json:"image_url"`
	Servings     sql.NullInt32  `json:"servings"`
	PrepTimeSec  sql.NullInt32  `json:"prep_time_sec"`
	CookTimeSec  sql.NullInt32  `json:"cook_time_sec"`
	TotalTimeSec sql.NullInt32  `json:"total_time_sec"`
	Category     sql.NullString `json:"category"`
	Cuisine      sql.NullString `json:"cuisine"`
	Attribution  sql.NullString `json:"attribution"`
	Rating       sql.NullString `json:"rating"`
	RatingCount  sql.NullInt32  `json:"rating_count"`
	LicenseNote  sql.NullString `json:"license_note"`
	ImportedAt   time.Time      `json:"imported_at"`
	Status       string         `json:"status"`
}

func (q *Queries) SaveImportCandidate(ctx context.Context, arg SaveImportCandidateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, saveImportCandidate,
		arg.ID,
		arg.SourceID,
		arg.SourceUrl,
		arg.ExternalID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Servings,
		arg.PrepTimeSec,
		arg.CookTimeSec,
		arg.TotalTimeSec,
		arg.Category,
		arg.Cuisine,
		arg.Attribution,
		arg.Rating,
		arg.RatingCount,
		arg.LicenseNote,
		arg.ImportedAt,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setCandidatePromoted = `-- name: SetCandidatePromoted :exec
UPDATE recipe_import_candidate
SET status = 'promoted', promoted_variant_id = $2
WHERE id = $1
`

type SetCandidatePromotedParams struct {
	ID                uuid.UUID     `json:"id"`
	PromotedVariantID uuid.NullUUID `json:"promoted_variant_id"`
}

func (q *Queries) SetCandidatePromoted(ctx context.Context, arg SetCandidatePromotedParams) error {
	_, err := q.db.ExecContext(ctx, setCandidatePromoted, arg.ID, arg.PromotedVariantID)
	return err
}

const setCandidateStatus = `-- name: SetCandidateStatus :exec
UPDATE recipe_import_candidate SET status = $2 WHERE id = $1
`

type SetCandidateStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetCandidateStatus(ctx context.Context, arg SetCandidateStatusParams) error {
	_, err := q.db.ExecContext(ctx, setCandidateStatus, arg.ID, arg.Status)
	return err
}

const upsertExternalRecipeSource = `-- name: UpsertExternalRecipeSource :exec
INSERT INTO external_recipe_source (id, name, kind, base_url, license_note, decision, enabled, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    kind = EXCLUDED.kind,
    base_url = EXCLUDED.base_url,
    license_note = EXCLUDED.license_note,
    decision = EXCLUDED.decision,
    enabled = EXCLUDED.enabled
`

type UpsertExternalRecipeSourceParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	BaseUrl     sql.NullString `json:"base_url"`
	LicenseNote sql.NullString `json:"license_note"`
	Decision    string         `json:"decision"`
	Enabled     bool           `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) UpsertExternalRecipeSource(ctx context.Context, arg UpsertExternalRecipeSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalRecipeSource,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.LicenseNote,
		arg.Decision,
		arg.Enabled,
		arg.CreatedAt,
	)
	return err
}
