// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopping.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOrUpdateRetailerListBinding = `-- name: CreateOrUpdateRetailerListBinding :exec
INSERT INTO retailer_list_binding (shopping_list_id, retailer, external_list_id, sync_direction, last_pushed_at, last_push_status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (shopping_list_id, retailer) DO UPDATE
SET external_list_id = EXCLUDED.external_list_id,
    sync_direction = EXCLUDED.sync_direction,
    last_pushed_at = EXCLUDED.last_pushed_at,
    last_push_status = EXCLUDED.last_push_status
`

type CreateOrUpdateRetailerListBindingParams struct {
	ShoppingListID uuid.UUID      `json:"shopping_list_id"`
	Retailer       string         `json:"retailer"`
	ExternalListID string         `json:"external_list_id"`
	SyncDirection  string         `json:"sync_direction"`
	LastPushedAt   sql.NullTime   `json:"last_pushed_at"`
	LastPushStatus sql.NullString `json:"last_push_status"`
}

func (q *Queries) CreateOrUpdateRetailerListBinding(ctx context.Context, arg CreateOrUpdateRetailerListBindingParams) error {
	_, err := q.db.ExecContext(ctx, createOrUpdateRetailerListBinding,
		arg.ShoppingListID,
		arg.Retailer,
		arg.ExternalListID,
		arg.SyncDirection,
		arg.LastPushedAt,
		arg.LastPushStatus,
	)
	return err
}

const createShoppingList = `-- name: CreateShoppingList :one
INSERT INTO shopping_list (id, owner_person_id, name, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateShoppingListParams struct {
	ID            uuid.UUID     `json:"id"`
	OwnerPersonID uuid.NullUUID `json:"owner_person_id"`
	Name          string        `json:"name"`
	Status        string        `json:"status"`
	CreatedAt     time.Time     `json:"created_at"`
}

func (q *Queries) CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createShoppingList,
		arg.ID,
		arg.OwnerPersonID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createShoppingListItem = `-- name: CreateShoppingListItem :exec
INSERT INTO shopping_list_item (id, shopping_list_id, shopping_requirement_id, ingredient_id, label, quantity, unit, checked, added_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateShoppingListItemParams struct {
	ID                    uuid.UUID      `json:"id"`
	ShoppingListID        uuid.UUID      `json:"shopping_list_id"`
	ShoppingRequirementID uuid.NullUUID  `json:"shopping_requirement_id"`
	IngredientID          uuid.NullUUID  `json:"ingredient_id"`
	Label                 sql.NullString `json:"label"`
	Quantity              string         `json:"quantity"`
	Unit                  string         `json:"unit"`
	Checked               bool           `json:"checked"`
	AddedAt               time.Time      `json:"added_at"`
}

func (q *Queries) CreateShoppingListItem(ctx context.Context, arg CreateShoppingListItemParams) error {
	_, err := q.db.ExecContext(ctx, createShoppingListItem,
		arg.ID,
		arg.ShoppingListID,
		arg.ShoppingRequirementID,
		arg.IngredientID,
		arg.Label,
		arg.Quantity,
		arg.Unit,
		arg.Checked,
		arg.AddedAt,
	)
	return err
}

const listShoppingListItems = `-- name: ListShoppingListItems :many
SELECT id, shopping_list_id, shopping_requirement_id, ingredient_id, label, quantity, unit, checked, added_at
FROM shopping_list_item
WHERE shopping_list_id = $1
ORDER BY ingredient_id
`

type ListShoppingListItemsRow struct {
	ID                    uuid.UUID      `json:"id"`
	ShoppingListID        uuid.UUID      `json:"shopping_list_id"`
	ShoppingRequirementID uuid.NullUUID  `json:"shopping_requirement_id"`
	IngredientID          uuid.NullUUID  `json:"ingredient_id"`
	Label                 sql.NullString `json:"label"`
	Quantity              string         `json:"quantity"`
	Unit                  string         `json:"unit"`
	Checked               bool           `json:"checked"`
	AddedAt               time.Time      `json:"added_at"`
}

func (q *Queries) ListShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) ([]ListShoppingListItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingListItems, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShoppingListItemsRow
	for rows.Next() {
		var i ListShoppingListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.ShoppingRequirementID,
			&i.IngredientID,
			&i.Label,
			&i.Quantity,
			&i.Unit,
			&i.Checked,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingLists = `-- name: ListShoppingLists :many
SELECT id, owner_person_id, name, status, created_at
FROM shopping_list
ORDER BY created_at DESC
`

func (q *Queries) ListShoppingLists(ctx context.Context) ([]ShoppingList, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(
			&i.ID,
			&i.OwnerPersonID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
