// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteIngredientAlias = `-- name: DeleteIngredientAlias :exec
DELETE FROM ingredient_alias
WHERE household_id = $1 AND alias = $2
`

type DeleteIngredientAliasParams struct {
	HouseholdID uuid.NullUUID `json:"household_id"`
	Alias       string        `json:"alias"`
}

func (q *Queries) DeleteIngredientAlias(ctx context.Context, arg DeleteIngredientAliasParams) error {
	_, err := q.db.ExecContext(ctx, deleteIngredientAlias, arg.HouseholdID, arg.Alias)
	return err
}

const getIngredientAlias = `-- name: GetIngredientAlias :one
SELECT id, household_id, alias, ingredient_id, created_at
FROM ingredient_alias
WHERE household_id = $1 AND alias = $2
`

type GetIngredientAliasParams struct {
	HouseholdID uuid.NullUUID `json:"household_id"`
	Alias       string        `json:"alias"`
}

func (q *Queries) GetIngredientAlias(ctx context.Context, arg GetIngredientAliasParams) (IngredientAlias, error) {
	row := q.db.QueryRowContext(ctx, getIngredientAlias, arg.HouseholdID, arg.Alias)
	var i IngredientAlias
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Alias,
		&i.IngredientID,
		&i.CreatedAt,
	)
	return i, err
}

const listIngredientAliases = `-- name: ListIngredientAliases :many
SELECT id, household_id, alias, ingredient_id, created_at
FROM ingredient_alias
WHERE household_id = $1
ORDER BY alias
`

func (q *Queries) ListIngredientAliases(ctx context.Context, householdID uuid.NullUUID) ([]IngredientAlias, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientAliases, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientAlias
	for rows.Next() {
		var i IngredientAlias
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Alias,
			&i.IngredientID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIngredientAlias = `-- name: ResolveIngredientAlias :one
SELECT ingredient_id
FROM ingredient_alias
WHERE household_id = $1 AND alias = $2
`

type ResolveIngredientAliasParams struct {
	HouseholdID uuid.NullUUID `json:"household_id"`
	Alias       string        `json:"alias"`
}

func (q *Queries) ResolveIngredientAlias(ctx context.Context, arg ResolveIngredientAliasParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, resolveIngredientAlias, arg.HouseholdID, arg.Alias)
	var ingredient_id uuid.UUID
	err := row.Scan(&ingredient_id)
	return ingredient_id, err
}

const upsertIngredientAlias = `-- name: UpsertIngredientAlias :exec
INSERT INTO ingredient_alias (id, household_id, alias, ingredient_id, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (household_id, alias) DO UPDATE
SET ingredient_id = EXCLUDED.ingredient_id
`

type UpsertIngredientAliasParams struct {
	ID           uuid.UUID     `json:"id"`
	HouseholdID  uuid.NullUUID `json:"household_id"`
	Alias        string        `json:"alias"`
	IngredientID uuid.UUID     `json:"ingredient_id"`
	CreatedAt    time.Time     `json:"created_at"`
}

func (q *Queries) UpsertIngredientAlias(ctx context.Context, arg UpsertIngredientAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertIngredientAlias,
		arg.ID,
		arg.HouseholdID,
		arg.Alias,
		arg.IngredientID,
		arg.CreatedAt,
	)
	return err
}
