// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanStatus.
const (
	MealPlanStatusApproved MealPlanStatus = "approved"
	MealPlanStatusArchived MealPlanStatus = "archived"
	MealPlanStatusDraft    MealPlanStatus = "draft"
)

// Valid indicates whether the value is a known member of the MealPlanStatus enum.
func (e MealPlanStatus) Valid() bool {
	switch e {
	case MealPlanStatusApproved:
		return true
	case MealPlanStatusArchived:
		return true
	case MealPlanStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanUpdateStatus.
const (
	MealPlanUpdateStatusApproved MealPlanUpdateStatus = "approved"
	MealPlanUpdateStatusArchived MealPlanUpdateStatus = "archived"
	MealPlanUpdateStatusDraft    MealPlanUpdateStatus = "draft"
)

// Valid indicates whether the value is a known member of the MealPlanUpdateStatus enum.
func (e MealPlanUpdateStatus) Valid() bool {
	switch e {
	case MealPlanUpdateStatusApproved:
		return true
	case MealPlanUpdateStatusArchived:
		return true
	case MealPlanUpdateStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for OrderSource.
const (
	Manual        OrderSource = "manual"
	ReceiptImport OrderSource = "receipt_import"
	RetailerApi   OrderSource = "retailer_api"
)

// Valid indicates whether the value is a known member of the OrderSource enum.
func (e OrderSource) Valid() bool {
	switch e {
	case Manual:
		return true
	case ReceiptImport:
		return true
	case RetailerApi:
		return true
	default:
		return false
	}
}

// Defines values for PlanRunResultStatus.
const (
	Accepted PlanRunResultStatus = "accepted"
	Failed   PlanRunResultStatus = "failed"
)

// Valid indicates whether the value is a known member of the PlanRunResultStatus enum.
func (e PlanRunResultStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Failed:
		return true
	default:
		return false
	}
}

// Defines values for RetailerListBindingLastPushStatus.
const (
	RetailerListBindingLastPushStatusError   RetailerListBindingLastPushStatus = "error"
	RetailerListBindingLastPushStatusSuccess RetailerListBindingLastPushStatus = "success"
)

// Valid indicates whether the value is a known member of the RetailerListBindingLastPushStatus enum.
func (e RetailerListBindingLastPushStatus) Valid() bool {
	switch e {
	case RetailerListBindingLastPushStatusError:
		return true
	case RetailerListBindingLastPushStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for RetailerListBindingSyncDirection.
const (
	Outbound RetailerListBindingSyncDirection = "outbound"
)

// Valid indicates whether the value is a known member of the RetailerListBindingSyncDirection enum.
func (e RetailerListBindingSyncDirection) Valid() bool {
	switch e {
	case Outbound:
		return true
	default:
		return false
	}
}

// Defines values for ShoppingCartStatus.
const (
	Abandoned ShoppingCartStatus = "abandoned"
	Confirmed ShoppingCartStatus = "confirmed"
	Created   ShoppingCartStatus = "created"
)

// Valid indicates whether the value is a known member of the ShoppingCartStatus enum.
func (e ShoppingCartStatus) Valid() bool {
	switch e {
	case Abandoned:
		return true
	case Confirmed:
		return true
	case Created:
		return true
	default:
		return false
	}
}

// Defines values for ShoppingListStatus.
const (
	ShoppingListStatusActive   ShoppingListStatus = "active"
	ShoppingListStatusArchived ShoppingListStatus = "archived"
)

// Valid indicates whether the value is a known member of the ShoppingListStatus enum.
func (e ShoppingListStatus) Valid() bool {
	switch e {
	case ShoppingListStatusActive:
		return true
	case ShoppingListStatusArchived:
		return true
	default:
		return false
	}
}

// EffortProfile defines model for EffortProfile.
type EffortProfile struct {
	KitchenEnergy int `json:"kitchen_energy"`

	// Weekday 0=Sunday .. 6=Saturday
	Weekday int `json:"weekday"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status *HealthStatus `json:"status,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Ingredient defines model for Ingredient.
type Ingredient struct {
	Brand *string `json:"brand,omitempty"`

	// Display human-friendly name
	Display string  `json:"display"`
	Gtin    *string `json:"gtin,omitempty"`

	// Id canonical id
	Id string `json:"id"`

	// SlvNummer SLV nummer when source is slv
	SlvNummer *int `json:"slv_nummer,omitempty"`

	// Source upstream source (slv
	Source *string `json:"source,omitempty"`
}

// IngredientMapping defines model for IngredientMapping.
type IngredientMapping struct {
	ExternalId *string `json:"external_id,omitempty"`

	// IngredientId canonical ingredient id (see Ingredient.id)
	IngredientId string    `json:"ingredient_id"`
	MealieFoodId string    `json:"mealie_food_id"`
	NeedsReview  bool      `json:"needs_review"`
	SourceName   string    `json:"source_name"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// IngredientMappingResolve defines model for IngredientMappingResolve.
type IngredientMappingResolve struct {
	AcceptableForms *[]string `json:"acceptable_forms,omitempty"`
	IngredientId    string    `json:"ingredient_id"`
	PreferredForm   *string   `json:"preferred_form,omitempty"`
}

// IngredientNutrient defines model for IngredientNutrient.
type IngredientNutrient struct {
	// Name nutrient name
	Name string `json:"name"`

	// Unit unit
	Unit string `json:"unit"`

	// Value value per 100 g edible portion
	Value float64 `json:"value"`
}

// IngredientProduct defines model for IngredientProduct.
type IngredientProduct struct {
	Amount      *string `json:"amount,omitempty"`
	Brand       *string `json:"brand,omitempty"`
	Description *string `json:"description,omitempty"`
	Gtin        *string `json:"gtin,omitempty"`
	ImageUrl    *string `json:"image_url,omitempty"`
	Key         string  `json:"key"`
	Name        string  `json:"name"`
}

// MealEvent defines model for MealEvent.
type MealEvent struct {
	CreatedAt      time.Time          `json:"created_at"`
	Id             int                `json:"id"`
	MealieRecipeId string             `json:"mealie_recipe_id"`
	Reactions      []MealReaction     `json:"reactions"`
	ServedOn       openapi_types.Date `json:"served_on"`
}

// MealEventNew defines model for MealEventNew.
type MealEventNew struct {
	MealieRecipeId string             `json:"mealie_recipe_id"`
	Reactions      *[]MealReaction    `json:"reactions,omitempty"`
	ServedOn       openapi_types.Date `json:"served_on"`
}

// MealPlan defines model for MealPlan.
type MealPlan struct {
	CreatedAt time.Time      `json:"created_at"`
	Id        int            `json:"id"`
	Status    MealPlanStatus `json:"status"`

	// WeekStart Monday of the planned week
	WeekStart openapi_types.Date `json:"week_start"`
}

// MealPlanStatus defines model for MealPlan.Status.
type MealPlanStatus string

// MealPlanCandidate defines model for MealPlanCandidate.
type MealPlanCandidate struct {
	// Breakdown per-signal score breakdown (pref, effort, repeat, school, campaign, familiarity, novelty)
	Breakdown map[string]float64 `json:"breakdown"`
	Feasible  bool               `json:"feasible"`
	Id        int                `json:"id"`
	Rank      int                `json:"rank"`
	Recipe    RecipeRef          `json:"recipe"`
	Score     float64            `json:"score"`
	SlotDate  openapi_types.Date `json:"slot_date"`
}

// MealPlanDecision defines model for MealPlanDecision.
type MealPlanDecision struct {
	DecidedAt      *time.Time         `json:"decided_at,omitempty"`
	MealieRecipeId string             `json:"mealie_recipe_id"`
	PlanId         int                `json:"plan_id"`
	SlotDate       openapi_types.Date `json:"slot_date"`
}

// MealPlanNew defines model for MealPlanNew.
type MealPlanNew struct {
	WeekStart *openapi_types.Date `json:"week_start,omitempty"`
}

// MealPlanUpdate defines model for MealPlanUpdate.
type MealPlanUpdate struct {
	Status *MealPlanUpdateStatus `json:"status,omitempty"`
}

// MealPlanUpdateStatus defines model for MealPlanUpdate.Status.
type MealPlanUpdateStatus string

// MealPlanView defines model for MealPlanView.
type MealPlanView struct {
	Candidates []MealPlanCandidate `json:"candidates"`
	Decisions  *[]MealPlanDecision `json:"decisions,omitempty"`
	Plan       MealPlan            `json:"plan"`
}

// MealReaction defines model for MealReaction.
type MealReaction struct {
	PersonId  string `json:"person_id"`
	Sentiment int    `json:"sentiment"`
}

// Order defines model for Order.
type Order struct {
	Id             int         `json:"id"`
	OrderedAt      time.Time   `json:"ordered_at"`
	Retailer       string      `json:"retailer"`
	ShoppingCartId *int        `json:"shopping_cart_id,omitempty"`
	Source         OrderSource `json:"source"`
	TotalPrice     *float32    `json:"total_price,omitempty"`
}

// OrderSource defines model for Order.Source.
type OrderSource string

// OrderItem defines model for OrderItem.
type OrderItem struct {
	Id                   int      `json:"id"`
	OrderId              int      `json:"order_id"`
	Quantity             float32  `json:"quantity"`
	RetailerProductId    string   `json:"retailer_product_id"`
	SubstitutedForItemId *int     `json:"substituted_for_item_id,omitempty"`
	TotalPrice           *float32 `json:"total_price,omitempty"`
	UnitPrice            *float32 `json:"unit_price,omitempty"`
}

// OrderView defines model for OrderView.
type OrderView struct {
	Items []OrderItem `json:"items"`
	Order Order       `json:"order"`
}

// Person defines model for Person.
type Person struct {
	CreatedAt time.Time `json:"created_at"`

	// Id canonical id
	Id     string  `json:"id"`
	Name   string  `json:"name"`
	Weight float64 `json:"weight"`
}

// PersonNew defines model for PersonNew.
type PersonNew struct {
	Name   string   `json:"name"`
	Weight *float64 `json:"weight,omitempty"`
}

// PersonPreference defines model for PersonPreference.
type PersonPreference struct {
	Confidence float64 `json:"confidence"`
	PersonId   string  `json:"person_id"`

	// Sentiment -2 (strongly dislike) to 2 (love)
	Sentiment int       `json:"sentiment"`
	Tag       string    `json:"tag"`
	UpdatedAt time.Time `json:"updated_at"`
}

// PlanRunInput defines model for PlanRunInput.
type PlanRunInput struct {
	// CreateWishlist resolve products and create Willys wishlist
	CreateWishlist *bool `json:"create_wishlist,omitempty"`

	// Days number of dinners (default: 7)
	Days *int `json:"days,omitempty"`

	// Week ISO week, e.g. 2026-W31 (default: next week)
	Week *string `json:"week,omitempty"`
}

// PlanRunResult defines model for PlanRunResult.
type PlanRunResult struct {
	// Message human-readable result summary
	Message string `json:"message"`

	// Status accepted = queued, failed = error
	Status PlanRunResultStatus `json:"status"`

	// WeekStart Monday of the planned week
	WeekStart *openapi_types.Date `json:"week_start,omitempty"`
}

// PlanRunResultStatus accepted = queued, failed = error
type PlanRunResultStatus string

// PlanningConstraint defines model for PlanningConstraint.
type PlanningConstraint struct {
	// Active whether the constraint is active
	Active bool `json:"active"`
	Id     int  `json:"id"`

	// Kind constraint kind (e.g. avoid_tag
	Kind string `json:"kind"`

	// Value constraint value
	Value string `json:"value"`
}

// PlanningConstraintNew defines model for PlanningConstraintNew.
type PlanningConstraintNew struct {
	Active bool   `json:"active"`
	Kind   string `json:"kind"`
	Value  string `json:"value"`
}

// ReactionNew defines model for ReactionNew.
type ReactionNew struct {
	// Note optional free-text note
	Note *string `json:"note,omitempty"`

	// PersonId who is reacting
	PersonId string `json:"person_id"`

	// Sentiment -2 (hate) .. 2 (love)
	Sentiment int `json:"sentiment"`
}

// RecipeRef defines model for RecipeRef.
type RecipeRef struct {
	// Effort 1 (quick) to 3 (intense)
	Effort         int       `json:"effort"`
	LastSyncedAt   time.Time `json:"last_synced_at"`
	MealieRecipeId string    `json:"mealie_recipe_id"`
	Tags           []string  `json:"tags"`
	Title          string    `json:"title"`
}

// RetailerListBinding defines model for RetailerListBinding.
type RetailerListBinding struct {
	ExternalListId string                             `json:"external_list_id"`
	Id             int                                `json:"id"`
	LastPushStatus *RetailerListBindingLastPushStatus `json:"last_push_status,omitempty"`
	LastPushedAt   *time.Time                         `json:"last_pushed_at,omitempty"`
	Retailer       string                             `json:"retailer"`
	ShoppingListId int                                `json:"shopping_list_id"`
	SyncDirection  RetailerListBindingSyncDirection   `json:"sync_direction"`
}

// RetailerListBindingLastPushStatus defines model for RetailerListBinding.LastPushStatus.
type RetailerListBindingLastPushStatus string

// RetailerListBindingSyncDirection defines model for RetailerListBinding.SyncDirection.
type RetailerListBindingSyncDirection string

// ShoppingCart defines model for ShoppingCart.
type ShoppingCart struct {
	CreatedAt             time.Time          `json:"created_at"`
	Id                    int                `json:"id"`
	RetailerListBindingId int                `json:"retailer_list_binding_id"`
	Status                ShoppingCartStatus `json:"status"`
}

// ShoppingCartStatus defines model for ShoppingCart.Status.
type ShoppingCartStatus string

// ShoppingList defines model for ShoppingList.
type ShoppingList struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int       `json:"id"`
	Name      string    `json:"name"`

	// OwnerPersonId person who owns the list; null = shared
	OwnerPersonId *string            `json:"owner_person_id,omitempty"`
	Status        ShoppingListStatus `json:"status"`
}

// ShoppingListStatus defines model for ShoppingList.Status.
type ShoppingListStatus string

// ShoppingListItem defines model for ShoppingListItem.
type ShoppingListItem struct {
	AddedAt               time.Time `json:"added_at"`
	Checked               bool      `json:"checked"`
	Id                    int       `json:"id"`
	IngredientId          *string   `json:"ingredient_id,omitempty"`
	Label                 *string   `json:"label,omitempty"`
	Quantity              float32   `json:"quantity"`
	ShoppingListId        int       `json:"shopping_list_id"`
	ShoppingRequirementId *int      `json:"shopping_requirement_id,omitempty"`
	Unit                  string    `json:"unit"`
}

// ShoppingListItemNew defines model for ShoppingListItemNew.
type ShoppingListItemNew struct {
	IngredientId          *string `json:"ingredient_id,omitempty"`
	Label                 *string `json:"label,omitempty"`
	Quantity              float32 `json:"quantity"`
	ShoppingRequirementId *int    `json:"shopping_requirement_id,omitempty"`
	Unit                  string  `json:"unit"`
}

// ShoppingListNew defines model for ShoppingListNew.
type ShoppingListNew struct {
	Name          string  `json:"name"`
	OwnerPersonId *string `json:"owner_person_id,omitempty"`
}

// ShoppingRequirement defines model for ShoppingRequirement.
type ShoppingRequirement struct {
	AcceptableForms []string `json:"acceptable_forms"`
	Id              int      `json:"id"`
	IngredientId    string   `json:"ingredient_id"`
	PreferredForm   *string  `json:"preferred_form"`
	Quantity        float64  `json:"quantity"`
	Unit            string   `json:"unit"`
}

// Store defines model for Store.
type Store struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	RetailerId string `json:"retailer_id"`
}

// StoreOffer defines model for StoreOffer.
type StoreOffer struct {
	CurrentlyCarried  bool      `json:"currently_carried"`
	Id                int64     `json:"id"`
	RetailerProductId string    `json:"retailer_product_id"`
	StoreId           string    `json:"store_id"`
	UpdatedAt         time.Time `json:"updated_at"`
}

// TonightView Tonight's meal: the recipe + any reactions recorded so far
type TonightView struct {
	// Reactions reactions already recorded for today's meal event
	Reactions []MealReaction `json:"reactions"`
	Recipe    RecipeRef      `json:"recipe"`

	// ServedOn today's date
	ServedOn openapi_types.Date `json:"served_on"`
}

// OrderId defines model for OrderId.
type OrderId = int

// PersonId defines model for PersonId.
type PersonId = string

// PlanId defines model for PlanId.
type PlanId = int

// RecipeId defines model for RecipeId.
type RecipeId = string

// ShoppingListId defines model for ShoppingListId.
type ShoppingListId = int

// ShoppingListItemId defines model for ShoppingListItemId.
type ShoppingListItemId = int

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// SearchFoodParams defines parameters for SearchFood.
type SearchFoodParams struct {
	// Q name substring to match
	Q     string `form:"q" json:"q"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	Retailer *string `form:"retailer,omitempty" json:"retailer,omitempty"`
	CartId   *int    `form:"cartId,omitempty" json:"cartId,omitempty"`
}

// SetDecisionsJSONBody defines parameters for SetDecisions.
type SetDecisionsJSONBody = []MealPlanDecision

// ListPreferencesParams defines parameters for ListPreferences.
type ListPreferencesParams struct {
	// PersonId filter to one person
	PersonId *string `form:"personId,omitempty" json:"personId,omitempty"`
}

// SearchProductsByGTINParams defines parameters for SearchProductsByGTIN.
type SearchProductsByGTINParams struct {
	Gtin string `form:"gtin" json:"gtin"`
}

// SearchProductsParams defines parameters for SearchProducts.
type SearchProductsParams struct {
	Q string `form:"q" json:"q"`
}

// ToggleShoppingListItemJSONBody defines parameters for ToggleShoppingListItem.
type ToggleShoppingListItemJSONBody struct {
	Checked bool `json:"checked"`
}

// PushShoppingListParams defines parameters for PushShoppingList.
type PushShoppingListParams struct {
	// Retailer which retailer to push to
	Retailer *string `form:"retailer,omitempty" json:"retailer,omitempty"`
}

// ToCartParams defines parameters for ToCart.
type ToCartParams struct {
	Retailer *string `form:"retailer,omitempty" json:"retailer,omitempty"`
}

// CreatePlanningConstraintJSONRequestBody defines body for CreatePlanningConstraint for application/json ContentType.
type CreatePlanningConstraintJSONRequestBody = PlanningConstraintNew

// UpsertEffortProfileJSONRequestBody defines body for UpsertEffortProfile for application/json ContentType.
type UpsertEffortProfileJSONRequestBody = EffortProfile

// ResolveIngredientMappingJSONRequestBody defines body for ResolveIngredientMapping for application/json ContentType.
type ResolveIngredientMappingJSONRequestBody = IngredientMappingResolve

// CreateMealEventJSONRequestBody defines body for CreateMealEvent for application/json ContentType.
type CreateMealEventJSONRequestBody = MealEventNew

// CreatePersonJSONRequestBody defines body for CreatePerson for application/json ContentType.
type CreatePersonJSONRequestBody = PersonNew

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = MealPlanNew

// RunPlanJSONRequestBody defines body for RunPlan for application/json ContentType.
type RunPlanJSONRequestBody = PlanRunInput

// UpdatePlanJSONRequestBody defines body for UpdatePlan for application/json ContentType.
type UpdatePlanJSONRequestBody = MealPlanUpdate

// SetDecisionsJSONRequestBody defines body for SetDecisions for application/json ContentType.
type SetDecisionsJSONRequestBody = SetDecisionsJSONBody

// CreateReactionJSONRequestBody defines body for CreateReaction for application/json ContentType.
type CreateReactionJSONRequestBody = ReactionNew

// CreateShoppingListJSONRequestBody defines body for CreateShoppingList for application/json ContentType.
type CreateShoppingListJSONRequestBody = ShoppingListNew

// AddShoppingListItemJSONRequestBody defines body for AddShoppingListItem for application/json ContentType.
type AddShoppingListItemJSONRequestBody = ShoppingListItemNew

// ToggleShoppingListItemJSONRequestBody defines body for ToggleShoppingListItem for application/json ContentType.
type ToggleShoppingListItemJSONRequestBody ToggleShoppingListItemJSONBody
