// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ImportCandidateStatus.
const (
	ImportCandidateStatusCandidate ImportCandidateStatus = "candidate"
	ImportCandidateStatusPromoted  ImportCandidateStatus = "promoted"
	ImportCandidateStatusRejected  ImportCandidateStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ImportCandidateStatus enum.
func (e ImportCandidateStatus) Valid() bool {
	switch e {
	case ImportCandidateStatusCandidate:
		return true
	case ImportCandidateStatusPromoted:
		return true
	case ImportCandidateStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanStatus.
const (
	MealPlanStatusApproved MealPlanStatus = "approved"
	MealPlanStatusArchived MealPlanStatus = "archived"
	MealPlanStatusDraft    MealPlanStatus = "draft"
)

// Valid indicates whether the value is a known member of the MealPlanStatus enum.
func (e MealPlanStatus) Valid() bool {
	switch e {
	case MealPlanStatusApproved:
		return true
	case MealPlanStatusArchived:
		return true
	case MealPlanStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanCandidateSlotKind.
const (
	MealPlanCandidateSlotKindBreakfast MealPlanCandidateSlotKind = "breakfast"
	MealPlanCandidateSlotKindDinner    MealPlanCandidateSlotKind = "dinner"
	MealPlanCandidateSlotKindSnack     MealPlanCandidateSlotKind = "snack"
)

// Valid indicates whether the value is a known member of the MealPlanCandidateSlotKind enum.
func (e MealPlanCandidateSlotKind) Valid() bool {
	switch e {
	case MealPlanCandidateSlotKindBreakfast:
		return true
	case MealPlanCandidateSlotKindDinner:
		return true
	case MealPlanCandidateSlotKindSnack:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanDecisionSlotKind.
const (
	MealPlanDecisionSlotKindBreakfast MealPlanDecisionSlotKind = "breakfast"
	MealPlanDecisionSlotKindDinner    MealPlanDecisionSlotKind = "dinner"
	MealPlanDecisionSlotKindSnack     MealPlanDecisionSlotKind = "snack"
)

// Valid indicates whether the value is a known member of the MealPlanDecisionSlotKind enum.
func (e MealPlanDecisionSlotKind) Valid() bool {
	switch e {
	case MealPlanDecisionSlotKindBreakfast:
		return true
	case MealPlanDecisionSlotKindDinner:
		return true
	case MealPlanDecisionSlotKindSnack:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanUpdateStatus.
const (
	MealPlanUpdateStatusApproved MealPlanUpdateStatus = "approved"
	MealPlanUpdateStatusArchived MealPlanUpdateStatus = "archived"
	MealPlanUpdateStatusDraft    MealPlanUpdateStatus = "draft"
)

// Valid indicates whether the value is a known member of the MealPlanUpdateStatus enum.
func (e MealPlanUpdateStatus) Valid() bool {
	switch e {
	case MealPlanUpdateStatusApproved:
		return true
	case MealPlanUpdateStatusArchived:
		return true
	case MealPlanUpdateStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for OrderSource.
const (
	Manual        OrderSource = "manual"
	ReceiptImport OrderSource = "receipt_import"
	RetailerApi   OrderSource = "retailer_api"
)

// Valid indicates whether the value is a known member of the OrderSource enum.
func (e OrderSource) Valid() bool {
	switch e {
	case Manual:
		return true
	case ReceiptImport:
		return true
	case RetailerApi:
		return true
	default:
		return false
	}
}

// Defines values for PlanProgressPhase.
const (
	Done      PlanProgressPhase = "done"
	Planning  PlanProgressPhase = "planning"
	Resolving PlanProgressPhase = "resolving"
	Started   PlanProgressPhase = "started"
	Wishlist  PlanProgressPhase = "wishlist"
)

// Valid indicates whether the value is a known member of the PlanProgressPhase enum.
func (e PlanProgressPhase) Valid() bool {
	switch e {
	case Done:
		return true
	case Planning:
		return true
	case Resolving:
		return true
	case Started:
		return true
	case Wishlist:
		return true
	default:
		return false
	}
}

// Defines values for PlanRunResultStatus.
const (
	Accepted PlanRunResultStatus = "accepted"
	Failed   PlanRunResultStatus = "failed"
)

// Valid indicates whether the value is a known member of the PlanRunResultStatus enum.
func (e PlanRunResultStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Failed:
		return true
	default:
		return false
	}
}

// Defines values for PromoteCandidateResponseCandidateStatus.
const (
	PromoteCandidateResponseCandidateStatusPromoted PromoteCandidateResponseCandidateStatus = "promoted"
)

// Valid indicates whether the value is a known member of the PromoteCandidateResponseCandidateStatus enum.
func (e PromoteCandidateResponseCandidateStatus) Valid() bool {
	switch e {
	case PromoteCandidateResponseCandidateStatusPromoted:
		return true
	default:
		return false
	}
}

// Defines values for RetailerListBindingLastPushStatus.
const (
	RetailerListBindingLastPushStatusError   RetailerListBindingLastPushStatus = "error"
	RetailerListBindingLastPushStatusSuccess RetailerListBindingLastPushStatus = "success"
)

// Valid indicates whether the value is a known member of the RetailerListBindingLastPushStatus enum.
func (e RetailerListBindingLastPushStatus) Valid() bool {
	switch e {
	case RetailerListBindingLastPushStatusError:
		return true
	case RetailerListBindingLastPushStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for RetailerListBindingSyncDirection.
const (
	Outbound RetailerListBindingSyncDirection = "outbound"
)

// Valid indicates whether the value is a known member of the RetailerListBindingSyncDirection enum.
func (e RetailerListBindingSyncDirection) Valid() bool {
	switch e {
	case Outbound:
		return true
	default:
		return false
	}
}

// Defines values for ShoppingCartStatus.
const (
	Abandoned ShoppingCartStatus = "abandoned"
	Confirmed ShoppingCartStatus = "confirmed"
	Created   ShoppingCartStatus = "created"
)

// Valid indicates whether the value is a known member of the ShoppingCartStatus enum.
func (e ShoppingCartStatus) Valid() bool {
	switch e {
	case Abandoned:
		return true
	case Confirmed:
		return true
	case Created:
		return true
	default:
		return false
	}
}

// Defines values for ShoppingListStatus.
const (
	ShoppingListStatusActive   ShoppingListStatus = "active"
	ShoppingListStatusArchived ShoppingListStatus = "archived"
)

// Valid indicates whether the value is a known member of the ShoppingListStatus enum.
func (e ShoppingListStatus) Valid() bool {
	switch e {
	case ShoppingListStatusActive:
		return true
	case ShoppingListStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for StorePricePriceKind.
const (
	Campaign StorePricePriceKind = "campaign"
	Member   StorePricePriceKind = "member"
	Regular  StorePricePriceKind = "regular"
)

// Valid indicates whether the value is a known member of the StorePricePriceKind enum.
func (e StorePricePriceKind) Valid() bool {
	switch e {
	case Campaign:
		return true
	case Member:
		return true
	case Regular:
		return true
	default:
		return false
	}
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	Expiring []DashboardExpiringLot `json:"expiring"`
	Pantry   DashboardPantry        `json:"pantry"`
	Tonight  *DashboardTonight      `json:"tonight,omitempty"`
}

// DashboardExpiringLot defines model for DashboardExpiringLot.
type DashboardExpiringLot struct {
	BestBefore   *time.Time `json:"best_before,omitempty"`
	IngredientId string     `json:"ingredient_id"`
	Quantity     float32    `json:"quantity"`
	Unit         string     `json:"unit"`
}

// DashboardPantry defines model for DashboardPantry.
type DashboardPantry struct {
	Expiring  int `json:"expiring"`
	Locations int `json:"locations"`
	Lots      int `json:"lots"`
}

// DashboardTonight defines model for DashboardTonight.
type DashboardTonight struct {
	Recipe   RecipeRef `json:"recipe"`
	ServedOn string    `json:"served_on"`
}

// DiscoverRecipeRequest defines model for DiscoverRecipeRequest.
type DiscoverRecipeRequest struct {
	// SourceId defaults to web-jsonld when omitted
	SourceId *string `json:"source_id,omitempty"`

	// Url absolute http(s) URL of the recipe page
	Url string `json:"url"`
}

// EffortProfile defines model for EffortProfile.
type EffortProfile struct {
	KitchenEnergy int `json:"kitchen_energy"`

	// Weekday 0=Sunday .. 6=Saturday
	Weekday int `json:"weekday"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Favorite defines model for Favorite.
type Favorite struct {
	CreatedAt      time.Time `json:"created_at"`
	HouseholdId    *string   `json:"household_id,omitempty"`
	Id             int       `json:"id"`
	MealieRecipeId string    `json:"mealie_recipe_id"`
	PersonId       *string   `json:"person_id,omitempty"`
}

// FavoriteNew defines model for FavoriteNew.
type FavoriteNew struct {
	HouseholdId *string `json:"household_id,omitempty"`

	// PersonId set exactly one of person_id / household_id
	PersonId *string `json:"person_id,omitempty"`
}

// GrocyProduct defines model for GrocyProduct.
type GrocyProduct struct {
	Barcode        *string  `json:"barcode,omitempty"`
	Id             int      `json:"id"`
	LocationId     *int     `json:"location_id,omitempty"`
	MinStockAmount *float32 `json:"min_stock_amount,omitempty"`
	Name           string   `json:"name"`
	QuIdPurchase   *int     `json:"qu_id_purchase,omitempty"`
	QuIdStock      *int     `json:"qu_id_stock,omitempty"`
}

// GrocyShoppingItem defines model for GrocyShoppingItem.
type GrocyShoppingItem struct {
	Amount float32 `json:"amount"`
	Done   bool    `json:"done"`
	Id     int     `json:"id"`
	Note   string  `json:"note"`

	// ProductId 0 for a free-text item
	ProductId int `json:"product_id"`
	QuId      int `json:"qu_id"`
}

// GrocyStatus defines model for GrocyStatus.
type GrocyStatus struct {
	BaseUrl    *string `json:"base_url,omitempty"`
	Configured bool    `json:"configured"`
	Reachable  bool    `json:"reachable"`
	Version    *string `json:"version,omitempty"`
}

// GrocyStockEntry defines model for GrocyStockEntry.
type GrocyStockEntry struct {
	Amount float32 `json:"amount"`

	// BestBefore YYYY-MM-DD
	BestBefore  *string `json:"best_before,omitempty"`
	Id          int     `json:"id"`
	LocationId  int     `json:"location_id"`
	ProductId   int     `json:"product_id"`
	ProductName string  `json:"product_name"`
	QuId        int     `json:"qu_id"`
}

// Health defines model for Health.
type Health struct {
	Status *HealthStatus `json:"status,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ImportCandidate defines model for ImportCandidate.
type ImportCandidate struct {
	Attribution       *string                     `json:"attribution,omitempty"`
	Category          *string                     `json:"category,omitempty"`
	CookTimeSec       *int                        `json:"cook_time_sec,omitempty"`
	Cuisine           *string                     `json:"cuisine,omitempty"`
	Description       *string                     `json:"description,omitempty"`
	ExternalId        *string                     `json:"external_id,omitempty"`
	Id                string                      `json:"id"`
	ImageUrl          *string                     `json:"image_url,omitempty"`
	ImportedAt        time.Time                   `json:"imported_at"`
	Ingredients       []ImportCandidateIngredient `json:"ingredients"`
	LicenseNote       *string                     `json:"license_note,omitempty"`
	PrepTimeSec       *int                        `json:"prep_time_sec,omitempty"`
	PromotedVariantId *string                     `json:"promoted_variant_id,omitempty"`
	Rating            *float32                    `json:"rating,omitempty"`
	RatingCount       *int                        `json:"rating_count,omitempty"`
	Servings          *int                        `json:"servings,omitempty"`
	SourceId          string                      `json:"source_id"`
	SourceUrl         string                      `json:"source_url"`
	Status            ImportCandidateStatus       `json:"status"`
	Title             string                      `json:"title"`
	TotalTimeSec      *int                        `json:"total_time_sec,omitempty"`
}

// ImportCandidateStatus defines model for ImportCandidate.Status.
type ImportCandidateStatus string

// ImportCandidateIngredient defines model for ImportCandidateIngredient.
type ImportCandidateIngredient struct {
	IngredientId *string `json:"ingredient_id,omitempty"`
	LineNo       int     `json:"line_no"`

	// NeedsReview true when the line could not be fully resolved
	NeedsReview bool     `json:"needs_review"`
	Quantity    *float32 `json:"quantity,omitempty"`
	RawText     string   `json:"raw_text"`
	Unit        string   `json:"unit"`
}

// Ingredient defines model for Ingredient.
type Ingredient struct {
	Brand *string `json:"brand,omitempty"`

	// Display human-friendly name
	Display string  `json:"display"`
	Gtin    *string `json:"gtin,omitempty"`

	// Id canonical id
	Id string `json:"id"`

	// SlvNummer SLV nummer when source is slv
	SlvNummer *int `json:"slv_nummer,omitempty"`

	// Source upstream source (slv
	Source *string `json:"source,omitempty"`
}

// IngredientAlias defines model for IngredientAlias.
type IngredientAlias struct {
	// Alias normalized nickname
	Alias     string    `json:"alias"`
	CreatedAt time.Time `json:"created_at"`

	// HouseholdId empty/null = global alias
	HouseholdId  *string `json:"household_id,omitempty"`
	Id           int64   `json:"id"`
	IngredientId string  `json:"ingredient_id"`
}

// IngredientAliasNew defines model for IngredientAliasNew.
type IngredientAliasNew struct {
	Alias string `json:"alias"`

	// HouseholdId empty = global alias
	HouseholdId  *string `json:"household_id,omitempty"`
	IngredientId string  `json:"ingredient_id"`
}

// IngredientMapping defines model for IngredientMapping.
type IngredientMapping struct {
	ExternalId *string `json:"external_id,omitempty"`

	// IngredientId canonical ingredient id (see Ingredient.id)
	IngredientId string    `json:"ingredient_id"`
	MealieFoodId string    `json:"mealie_food_id"`
	NeedsReview  bool      `json:"needs_review"`
	SourceName   string    `json:"source_name"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// IngredientMappingResolve defines model for IngredientMappingResolve.
type IngredientMappingResolve struct {
	AcceptableForms *[]string `json:"acceptable_forms,omitempty"`
	IngredientId    string    `json:"ingredient_id"`
	PreferredForm   *string   `json:"preferred_form,omitempty"`
}

// IngredientNutrient defines model for IngredientNutrient.
type IngredientNutrient struct {
	// Name nutrient name
	Name string `json:"name"`

	// Unit unit
	Unit string `json:"unit"`

	// Value value per 100 g edible portion
	Value float64 `json:"value"`
}

// IngredientProduct defines model for IngredientProduct.
type IngredientProduct struct {
	Amount      *string `json:"amount,omitempty"`
	Brand       *string `json:"brand,omitempty"`
	Description *string `json:"description,omitempty"`
	Gtin        *string `json:"gtin,omitempty"`
	ImageUrl    *string `json:"image_url,omitempty"`
	Key         string  `json:"key"`
	Name        string  `json:"name"`
}

// InspirationSuggestion defines model for InspirationSuggestion.
type InspirationSuggestion struct {
	Effort int `json:"effort"`

	// MatchRatio 1 = fully cookable from pantry
	MatchRatio float64 `json:"match_ratio"`

	// MatchedIngredientIds recipe ingredients already in the pantry
	MatchedIngredientIds []string `json:"matched_ingredient_ids"`
	MealieRecipeId       string   `json:"mealie_recipe_id"`

	// MissingIngredientIds recipe ingredients still needed
	MissingIngredientIds []string `json:"missing_ingredient_ids"`
	Tags                 []string `json:"tags"`
	Title                string   `json:"title"`
	TotalIngredients     int      `json:"total_ingredients"`
}

// MealEvent defines model for MealEvent.
type MealEvent struct {
	CreatedAt      time.Time          `json:"created_at"`
	Id             int                `json:"id"`
	MealieRecipeId string             `json:"mealie_recipe_id"`
	Reactions      []MealReaction     `json:"reactions"`
	ServedOn       openapi_types.Date `json:"served_on"`
}

// MealEventNew defines model for MealEventNew.
type MealEventNew struct {
	MealieRecipeId string             `json:"mealie_recipe_id"`
	Reactions      *[]MealReaction    `json:"reactions,omitempty"`
	ServedOn       openapi_types.Date `json:"served_on"`
}

// MealPlan defines model for MealPlan.
type MealPlan struct {
	CreatedAt time.Time      `json:"created_at"`
	Id        int            `json:"id"`
	Status    MealPlanStatus `json:"status"`

	// WeekStart Monday of the planned week
	WeekStart openapi_types.Date `json:"week_start"`
}

// MealPlanStatus defines model for MealPlan.Status.
type MealPlanStatus string

// MealPlanCandidate defines model for MealPlanCandidate.
type MealPlanCandidate struct {
	// Breakdown per-signal score breakdown (pref, effort, repeat, school, campaign, familiarity, novelty)
	Breakdown map[string]float64        `json:"breakdown"`
	Feasible  bool                      `json:"feasible"`
	Id        int                       `json:"id"`
	Rank      int                       `json:"rank"`
	Recipe    RecipeRef                 `json:"recipe"`
	Score     float64                   `json:"score"`
	SlotDate  openapi_types.Date        `json:"slot_date"`
	SlotKind  MealPlanCandidateSlotKind `json:"slot_kind"`
}

// MealPlanCandidateSlotKind defines model for MealPlanCandidate.SlotKind.
type MealPlanCandidateSlotKind string

// MealPlanDecision defines model for MealPlanDecision.
type MealPlanDecision struct {
	DecidedAt      *time.Time                `json:"decided_at,omitempty"`
	MealieRecipeId string                    `json:"mealie_recipe_id"`
	PlanId         int                       `json:"plan_id"`
	SlotDate       openapi_types.Date        `json:"slot_date"`
	SlotKind       *MealPlanDecisionSlotKind `json:"slot_kind,omitempty"`
}

// MealPlanDecisionSlotKind defines model for MealPlanDecision.SlotKind.
type MealPlanDecisionSlotKind string

// MealPlanNew defines model for MealPlanNew.
type MealPlanNew struct {
	WeekStart *openapi_types.Date `json:"week_start,omitempty"`
}

// MealPlanUpdate defines model for MealPlanUpdate.
type MealPlanUpdate struct {
	Status *MealPlanUpdateStatus `json:"status,omitempty"`
}

// MealPlanUpdateStatus defines model for MealPlanUpdate.Status.
type MealPlanUpdateStatus string

// MealPlanView defines model for MealPlanView.
type MealPlanView struct {
	Candidates []MealPlanCandidate `json:"candidates"`
	Decisions  *[]MealPlanDecision `json:"decisions,omitempty"`
	Plan       MealPlan            `json:"plan"`
}

// MealReaction defines model for MealReaction.
type MealReaction struct {
	PersonId  string `json:"person_id"`
	Sentiment int    `json:"sentiment"`
}

// Order defines model for Order.
type Order struct {
	Id             int         `json:"id"`
	OrderedAt      time.Time   `json:"ordered_at"`
	Retailer       string      `json:"retailer"`
	ShoppingCartId *int        `json:"shopping_cart_id,omitempty"`
	Source         OrderSource `json:"source"`
	TotalPrice     *float32    `json:"total_price,omitempty"`
}

// OrderSource defines model for Order.Source.
type OrderSource string

// OrderItem defines model for OrderItem.
type OrderItem struct {
	Id                   int      `json:"id"`
	OrderId              int      `json:"order_id"`
	Quantity             float32  `json:"quantity"`
	RetailerProductId    string   `json:"retailer_product_id"`
	SubstitutedForItemId *int     `json:"substituted_for_item_id,omitempty"`
	TotalPrice           *float32 `json:"total_price,omitempty"`
	UnitPrice            *float32 `json:"unit_price,omitempty"`
}

// OrderView defines model for OrderView.
type OrderView struct {
	Items []OrderItem `json:"items"`
	Order Order       `json:"order"`
}

// PantryAdjustNew defines model for PantryAdjustNew.
type PantryAdjustNew struct {
	Estimated *bool   `json:"estimated,omitempty"`
	Quantity  float32 `json:"quantity"`
	Reason    *string `json:"reason,omitempty"`
	Source    string  `json:"source"`
}

// PantryDiscardNew defines model for PantryDiscardNew.
type PantryDiscardNew struct {
	Estimated *bool   `json:"estimated,omitempty"`
	Quantity  float32 `json:"quantity"`
	Reason    *string `json:"reason,omitempty"`
	Source    string  `json:"source"`
}

// PantryLot defines model for PantryLot.
type PantryLot struct {
	BestBefore   *time.Time `json:"best_before,omitempty"`
	Confidence   string     `json:"confidence"`
	CreatedAt    time.Time  `json:"created_at"`
	Id           string     `json:"id"`
	IngredientId string     `json:"ingredient_id"`
	LocationId   string     `json:"location_id"`
	OpenedAt     *time.Time `json:"opened_at,omitempty"`
	ProductId    string     `json:"product_id"`
	Quantity     float32    `json:"quantity"`
	Unit         string     `json:"unit"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// PantryOpenNew defines model for PantryOpenNew.
type PantryOpenNew struct {
	Source string `json:"source"`
}

// PantryTransferNew defines model for PantryTransferNew.
type PantryTransferNew struct {
	LocationId string  `json:"location_id"`
	Quantity   float32 `json:"quantity"`
	Source     string  `json:"source"`
}

// Person defines model for Person.
type Person struct {
	CreatedAt time.Time `json:"created_at"`

	// Id canonical id
	Id     string  `json:"id"`
	Name   string  `json:"name"`
	Weight float64 `json:"weight"`
}

// PersonNew defines model for PersonNew.
type PersonNew struct {
	Name   string   `json:"name"`
	Weight *float64 `json:"weight,omitempty"`
}

// PersonPreference defines model for PersonPreference.
type PersonPreference struct {
	Confidence float64 `json:"confidence"`
	PersonId   string  `json:"person_id"`

	// Sentiment -2 (strongly dislike) to 2 (love)
	Sentiment int       `json:"sentiment"`
	Tag       string    `json:"tag"`
	UpdatedAt time.Time `json:"updated_at"`
}

// PersonPreferenceNew defines model for PersonPreferenceNew.
type PersonPreferenceNew struct {
	Confidence float64 `json:"confidence"`
	PersonId   string  `json:"person_id"`

	// Sentiment -2 (strongly dislike) to 2 (love)
	Sentiment int    `json:"sentiment"`
	Tag       string `json:"tag"`
}

// PersonUpdate defines model for PersonUpdate.
type PersonUpdate struct {
	Name string `json:"name"`

	// Weight 0/omitted leaves the existing weight unchanged
	Weight *float64 `json:"weight,omitempty"`
}

// PlanProgress One SSE progress event for a running plan (POST /plans/run/stream). The payload shape is intentionally minimal and not finalized until the frontend's SSE consumer needs it (task 3.4).
type PlanProgress struct {
	// At when the phase was reached
	At time.Time `json:"at"`

	// Message human-readable progress detail
	Message string `json:"message"`

	// Phase the phase the run has reached
	Phase PlanProgressPhase `json:"phase"`
}

// PlanProgressPhase the phase the run has reached
type PlanProgressPhase string

// PlanRunInput defines model for PlanRunInput.
type PlanRunInput struct {
	// CreateWishlist resolve products and create Willys wishlist
	CreateWishlist *bool `json:"create_wishlist,omitempty"`

	// Days number of dinners (default: 7)
	Days *int `json:"days,omitempty"`

	// Week ISO week, e.g. 2026-W31 (default: next week)
	Week *string `json:"week,omitempty"`
}

// PlanRunResult defines model for PlanRunResult.
type PlanRunResult struct {
	// Message human-readable result summary
	Message string `json:"message"`

	// Status accepted = queued, failed = error
	Status PlanRunResultStatus `json:"status"`

	// WeekStart Monday of the planned week
	WeekStart *openapi_types.Date `json:"week_start,omitempty"`
}

// PlanRunResultStatus accepted = queued, failed = error
type PlanRunResultStatus string

// PlanningConstraint defines model for PlanningConstraint.
type PlanningConstraint struct {
	// Active whether the constraint is active
	Active bool `json:"active"`
	Id     int  `json:"id"`

	// Kind constraint kind (e.g. avoid_tag
	Kind string `json:"kind"`

	// Value constraint value
	Value string `json:"value"`
}

// PlanningConstraintNew defines model for PlanningConstraintNew.
type PlanningConstraintNew struct {
	Active bool   `json:"active"`
	Kind   string `json:"kind"`
	Value  string `json:"value"`
}

// ProductPriceGroup defines model for ProductPriceGroup.
type ProductPriceGroup struct {
	Cheapest          *StorePrice  `json:"cheapest,omitempty"`
	DisplayName       *string      `json:"display_name,omitempty"`
	Prices            []StorePrice `json:"prices"`
	ProductId         *string      `json:"product_id,omitempty"`
	RetailerId        string       `json:"retailer_id"`
	RetailerName      *string      `json:"retailer_name,omitempty"`
	RetailerProductId string       `json:"retailer_product_id"`
}

// PromoteCandidateRequest defines model for PromoteCandidateRequest.
type PromoteCandidateRequest struct {
	// FamilyId reuse an existing family; a new family is created when omitted
	FamilyId *string `json:"family_id,omitempty"`
}

// PromoteCandidateResponse defines model for PromoteCandidateResponse.
type PromoteCandidateResponse struct {
	CandidateStatus PromoteCandidateResponseCandidateStatus `json:"candidate_status"`
	FamilyId        string                                  `json:"family_id"`
	RevisionId      string                                  `json:"revision_id"`
	VariantId       string                                  `json:"variant_id"`
}

// PromoteCandidateResponseCandidateStatus defines model for PromoteCandidateResponse.CandidateStatus.
type PromoteCandidateResponseCandidateStatus string

// ReactionNew defines model for ReactionNew.
type ReactionNew struct {
	// Note optional free-text note
	Note *string `json:"note,omitempty"`

	// PersonId who is reacting
	PersonId string `json:"person_id"`

	// Sentiment -2 (hate) .. 2 (love)
	Sentiment int `json:"sentiment"`
}

// RecipeFamily defines model for RecipeFamily.
type RecipeFamily struct {
	Archived         bool      `json:"archived"`
	CreatedAt        time.Time `json:"created_at"`
	DefaultVariantId *string   `json:"default_variant_id,omitempty"`
	Description      *string   `json:"description,omitempty"`
	Id               string    `json:"id"`
	Name             string    `json:"name"`
}

// RecipeFamilyNew defines model for RecipeFamilyNew.
type RecipeFamilyNew struct {
	Description *string `json:"description,omitempty"`

	// Id slug; derived from name when omitted
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name"`
}

// RecipeIngredient defines model for RecipeIngredient.
type RecipeIngredient struct {
	AcceptableForms *[]string `json:"acceptable_forms,omitempty"`
	IngredientId    string    `json:"ingredient_id"`
	PreferredForm   *string   `json:"preferred_form,omitempty"`
	Quantity        float32   `json:"quantity"`
	RawText         *string   `json:"raw_text,omitempty"`
	Unit            string    `json:"unit"`
}

// RecipeRating defines model for RecipeRating.
type RecipeRating struct {
	Average        float32 `json:"average"`
	MealieRecipeId string  `json:"mealie_recipe_id"`
	ReviewCount    int     `json:"review_count"`
}

// RecipeRef defines model for RecipeRef.
type RecipeRef struct {
	// Effort 1 (quick) to 3 (intense)
	Effort         int       `json:"effort"`
	LastSyncedAt   time.Time `json:"last_synced_at"`
	MealieRecipeId string    `json:"mealie_recipe_id"`
	Tags           []string  `json:"tags"`
	Title          string    `json:"title"`
}

// RecipeRevision defines model for RecipeRevision.
type RecipeRevision struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          string             `json:"id"`
	Ingredients []RecipeIngredient `json:"ingredients"`
	Parents     *[]string          `json:"parents,omitempty"`
	Servings    *int               `json:"servings,omitempty"`
	Steps       []string           `json:"steps"`
	VariantId   string             `json:"variant_id"`
}

// RecipeRevisionNew defines model for RecipeRevisionNew.
type RecipeRevisionNew struct {
	Description *string            `json:"description,omitempty"`
	Ingredients []RecipeIngredient `json:"ingredients"`

	// ParentRevisionId derive from this revision
	ParentRevisionId *string  `json:"parent_revision_id,omitempty"`
	Servings         *int     `json:"servings,omitempty"`
	Steps            []string `json:"steps"`
}

// RecipeVariant defines model for RecipeVariant.
type RecipeVariant struct {
	Archived          bool      `json:"archived"`
	CreatedAt         time.Time `json:"created_at"`
	FamilyId          string    `json:"family_id"`
	Id                string    `json:"id"`
	SourceAttribution *string   `json:"source_attribution,omitempty"`
	Title             string    `json:"title"`
}

// RecipeVariantNew defines model for RecipeVariantNew.
type RecipeVariantNew struct {
	// Id slug; derived from title when omitted
	Id                *string `json:"id,omitempty"`
	SourceAttribution *string `json:"source_attribution,omitempty"`
	Title             string  `json:"title"`
}

// RetailerListBinding defines model for RetailerListBinding.
type RetailerListBinding struct {
	ExternalListId string                             `json:"external_list_id"`
	Id             int                                `json:"id"`
	LastPushStatus *RetailerListBindingLastPushStatus `json:"last_push_status,omitempty"`
	LastPushedAt   *time.Time                         `json:"last_pushed_at,omitempty"`
	Retailer       string                             `json:"retailer"`
	ShoppingListId int                                `json:"shopping_list_id"`
	SyncDirection  RetailerListBindingSyncDirection   `json:"sync_direction"`
}

// RetailerListBindingLastPushStatus defines model for RetailerListBinding.LastPushStatus.
type RetailerListBindingLastPushStatus string

// RetailerListBindingSyncDirection defines model for RetailerListBinding.SyncDirection.
type RetailerListBindingSyncDirection string

// ShoppingCart defines model for ShoppingCart.
type ShoppingCart struct {
	CreatedAt             time.Time          `json:"created_at"`
	Id                    int                `json:"id"`
	RetailerListBindingId int                `json:"retailer_list_binding_id"`
	Status                ShoppingCartStatus `json:"status"`
}

// ShoppingCartStatus defines model for ShoppingCart.Status.
type ShoppingCartStatus string

// ShoppingList defines model for ShoppingList.
type ShoppingList struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int       `json:"id"`
	Name      string    `json:"name"`

	// OwnerPersonId person who owns the list; null = shared
	OwnerPersonId *string            `json:"owner_person_id,omitempty"`
	Status        ShoppingListStatus `json:"status"`
}

// ShoppingListStatus defines model for ShoppingList.Status.
type ShoppingListStatus string

// ShoppingListItem defines model for ShoppingListItem.
type ShoppingListItem struct {
	AddedAt               time.Time `json:"added_at"`
	Checked               bool      `json:"checked"`
	Id                    int       `json:"id"`
	IngredientId          *string   `json:"ingredient_id,omitempty"`
	Label                 *string   `json:"label,omitempty"`
	Quantity              float32   `json:"quantity"`
	ShoppingListId        int       `json:"shopping_list_id"`
	ShoppingRequirementId *int      `json:"shopping_requirement_id,omitempty"`
	Unit                  string    `json:"unit"`
}

// ShoppingListItemNew defines model for ShoppingListItemNew.
type ShoppingListItemNew struct {
	IngredientId          *string `json:"ingredient_id,omitempty"`
	Label                 *string `json:"label,omitempty"`
	Quantity              float32 `json:"quantity"`
	ShoppingRequirementId *int    `json:"shopping_requirement_id,omitempty"`
	Unit                  string  `json:"unit"`
}

// ShoppingListNew defines model for ShoppingListNew.
type ShoppingListNew struct {
	Name          string  `json:"name"`
	OwnerPersonId *string `json:"owner_person_id,omitempty"`
}

// ShoppingRequirement defines model for ShoppingRequirement.
type ShoppingRequirement struct {
	AcceptableForms []string `json:"acceptable_forms"`
	Id              string   `json:"id"`
	IngredientId    string   `json:"ingredient_id"`
	IngredientName  *string  `json:"ingredient_name,omitempty"`
	PreferredForm   *string  `json:"preferred_form"`
	Quantity        float64  `json:"quantity"`
	Unit            string   `json:"unit"`
}

// Store defines model for Store.
type Store struct {
	DistanceKm   *float32 `json:"distance_km,omitempty"`
	Id           string   `json:"id"`
	Latitude     *float32 `json:"latitude,omitempty"`
	Longitude    *float32 `json:"longitude,omitempty"`
	Name         string   `json:"name"`
	RetailerId   string   `json:"retailer_id"`
	RetailerName *string  `json:"retailer_name,omitempty"`
}

// StoreOffer defines model for StoreOffer.
type StoreOffer struct {
	CurrentlyCarried  bool      `json:"currently_carried"`
	Id                int64     `json:"id"`
	RetailerProductId string    `json:"retailer_product_id"`
	StoreId           string    `json:"store_id"`
	UpdatedAt         time.Time `json:"updated_at"`
}

// StorePrice defines model for StorePrice.
type StorePrice struct {
	ObservedAt   time.Time           `json:"observed_at"`
	Price        float32             `json:"price"`
	PriceKind    StorePricePriceKind `json:"price_kind"`
	RetailerId   string              `json:"retailer_id"`
	RetailerName *string             `json:"retailer_name,omitempty"`
	Source       string              `json:"source"`
	StoreId      string              `json:"store_id"`
	StoreName    *string             `json:"store_name,omitempty"`
}

// StorePricePriceKind defines model for StorePrice.PriceKind.
type StorePricePriceKind string

// TonightView Tonight's meal: the recipe + any reactions recorded so far
type TonightView struct {
	// Reactions reactions already recorded for today's meal event
	Reactions []MealReaction `json:"reactions"`
	Recipe    RecipeRef      `json:"recipe"`

	// ServedOn today's date
	ServedOn openapi_types.Date `json:"served_on"`
}

// OrderId defines model for OrderId.
type OrderId = int

// PersonId defines model for PersonId.
type PersonId = string

// PlanId defines model for PlanId.
type PlanId = int

// RecipeId defines model for RecipeId.
type RecipeId = string

// ShoppingListId defines model for ShoppingListId.
type ShoppingListId = int

// ShoppingListItemId defines model for ShoppingListItemId.
type ShoppingListItemId = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// GrocyAddShoppingItemJSONBody defines parameters for GrocyAddShoppingItem.
type GrocyAddShoppingItemJSONBody struct {
	Amount float32 `json:"amount"`
	Note   *string `json:"note,omitempty"`

	// ProductId 0 for a free-text item
	ProductId *int `json:"product_id,omitempty"`
}

// GrocyAddStockJSONBody defines parameters for GrocyAddStock.
type GrocyAddStockJSONBody struct {
	Amount float32 `json:"amount"`

	// BestBefore YYYY-MM-DD
	BestBefore *string `json:"best_before,omitempty"`
	ProductId  int     `json:"product_id"`
}

// GrocyConsumeStockJSONBody defines parameters for GrocyConsumeStock.
type GrocyConsumeStockJSONBody struct {
	Amount    float32 `json:"amount"`
	ProductId int     `json:"product_id"`
}

// ListIngredientAliasesParams defines parameters for ListIngredientAliases.
type ListIngredientAliasesParams struct {
	HouseholdId *string `form:"householdId,omitempty" json:"householdId,omitempty"`
}

// ResolveIngredientAliasParams defines parameters for ResolveIngredientAlias.
type ResolveIngredientAliasParams struct {
	HouseholdId *string `form:"householdId,omitempty" json:"householdId,omitempty"`
}

// DeleteIngredientAliasParams defines parameters for DeleteIngredientAlias.
type DeleteIngredientAliasParams struct {
	HouseholdId *string `form:"householdId,omitempty" json:"householdId,omitempty"`
}

// SearchFoodParams defines parameters for SearchFood.
type SearchFoodParams struct {
	// Q name substring to match
	Q     string `form:"q" json:"q"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	Retailer *string `form:"retailer,omitempty" json:"retailer,omitempty"`
	CartId   *int    `form:"cartId,omitempty" json:"cartId,omitempty"`
}

// ListExpiringLotsParams defines parameters for ListExpiringLots.
type ListExpiringLotsParams struct {
	// WithinHours window in hours (default 168 = 7 days)
	WithinHours *int `form:"withinHours,omitempty" json:"withinHours,omitempty"`
}

// SetDecisionsJSONBody defines parameters for SetDecisions.
type SetDecisionsJSONBody = []MealPlanDecision

// ListPreferencesParams defines parameters for ListPreferences.
type ListPreferencesParams struct {
	// PersonId filter to one person
	PersonId *string `form:"personId,omitempty" json:"personId,omitempty"`
}

// SearchProductsByGTINParams defines parameters for SearchProductsByGTIN.
type SearchProductsByGTINParams struct {
	Gtin string `form:"gtin" json:"gtin"`
}

// SearchProductsParams defines parameters for SearchProducts.
type SearchProductsParams struct {
	Q string `form:"q" json:"q"`
}

// ListImportCandidatesParams defines parameters for ListImportCandidates.
type ListImportCandidatesParams struct {
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// ToggleShoppingListItemJSONBody defines parameters for ToggleShoppingListItem.
type ToggleShoppingListItemJSONBody struct {
	Checked bool `json:"checked"`
}

// PushShoppingListParams defines parameters for PushShoppingList.
type PushShoppingListParams struct {
	// Retailer which retailer to push to
	Retailer *string `form:"retailer,omitempty" json:"retailer,omitempty"`
}

// ToCartParams defines parameters for ToCart.
type ToCartParams struct {
	Retailer *string `form:"retailer,omitempty" json:"retailer,omitempty"`
}

// ListStoresParams defines parameters for ListStores.
type ListStoresParams struct {
	// Latitude origin latitude (WGS84); when set with longitude, stores are ranked nearest-first
	Latitude *float32 `form:"latitude,omitempty" json:"latitude,omitempty"`

	// Longitude origin longitude (WGS84)
	Longitude *float32 `form:"longitude,omitempty" json:"longitude,omitempty"`
}

// GetDashboardParams defines parameters for GetDashboard.
type GetDashboardParams struct {
	// HouseholdId household to build the dashboard for
	HouseholdId *string `form:"householdId,omitempty" json:"householdId,omitempty"`
}

// CreatePlanningConstraintJSONRequestBody defines body for CreatePlanningConstraint for application/json ContentType.
type CreatePlanningConstraintJSONRequestBody = PlanningConstraintNew

// UpsertEffortProfileJSONRequestBody defines body for UpsertEffortProfile for application/json ContentType.
type UpsertEffortProfileJSONRequestBody = EffortProfile

// GrocyAddShoppingItemJSONRequestBody defines body for GrocyAddShoppingItem for application/json ContentType.
type GrocyAddShoppingItemJSONRequestBody GrocyAddShoppingItemJSONBody

// GrocyAddStockJSONRequestBody defines body for GrocyAddStock for application/json ContentType.
type GrocyAddStockJSONRequestBody GrocyAddStockJSONBody

// GrocyConsumeStockJSONRequestBody defines body for GrocyConsumeStock for application/json ContentType.
type GrocyConsumeStockJSONRequestBody GrocyConsumeStockJSONBody

// CreateIngredientAliasJSONRequestBody defines body for CreateIngredientAlias for application/json ContentType.
type CreateIngredientAliasJSONRequestBody = IngredientAliasNew

// ResolveIngredientMappingJSONRequestBody defines body for ResolveIngredientMapping for application/json ContentType.
type ResolveIngredientMappingJSONRequestBody = IngredientMappingResolve

// CreateMealEventJSONRequestBody defines body for CreateMealEvent for application/json ContentType.
type CreateMealEventJSONRequestBody = MealEventNew

// AdjustPantryLotJSONRequestBody defines body for AdjustPantryLot for application/json ContentType.
type AdjustPantryLotJSONRequestBody = PantryAdjustNew

// DiscardPantryLotJSONRequestBody defines body for DiscardPantryLot for application/json ContentType.
type DiscardPantryLotJSONRequestBody = PantryDiscardNew

// OpenPantryLotJSONRequestBody defines body for OpenPantryLot for application/json ContentType.
type OpenPantryLotJSONRequestBody = PantryOpenNew

// TransferPantryLotJSONRequestBody defines body for TransferPantryLot for application/json ContentType.
type TransferPantryLotJSONRequestBody = PantryTransferNew

// CreatePersonJSONRequestBody defines body for CreatePerson for application/json ContentType.
type CreatePersonJSONRequestBody = PersonNew

// UpdatePersonJSONRequestBody defines body for UpdatePerson for application/json ContentType.
type UpdatePersonJSONRequestBody = PersonUpdate

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = MealPlanNew

// RunPlanJSONRequestBody defines body for RunPlan for application/json ContentType.
type RunPlanJSONRequestBody = PlanRunInput

// RunPlanStreamJSONRequestBody defines body for RunPlanStream for application/json ContentType.
type RunPlanStreamJSONRequestBody = PlanRunInput

// UpdatePlanJSONRequestBody defines body for UpdatePlan for application/json ContentType.
type UpdatePlanJSONRequestBody = MealPlanUpdate

// SetDecisionsJSONRequestBody defines body for SetDecisions for application/json ContentType.
type SetDecisionsJSONRequestBody = SetDecisionsJSONBody

// SetPreferenceJSONRequestBody defines body for SetPreference for application/json ContentType.
type SetPreferenceJSONRequestBody = PersonPreferenceNew

// CreateReactionJSONRequestBody defines body for CreateReaction for application/json ContentType.
type CreateReactionJSONRequestBody = ReactionNew

// CreateRecipeFamilyJSONRequestBody defines body for CreateRecipeFamily for application/json ContentType.
type CreateRecipeFamilyJSONRequestBody = RecipeFamilyNew

// CreateRecipeVariantJSONRequestBody defines body for CreateRecipeVariant for application/json ContentType.
type CreateRecipeVariantJSONRequestBody = RecipeVariantNew

// CreateRecipeRevisionJSONRequestBody defines body for CreateRecipeRevision for application/json ContentType.
type CreateRecipeRevisionJSONRequestBody = RecipeRevisionNew

// DiscoverRecipeJSONRequestBody defines body for DiscoverRecipe for application/json ContentType.
type DiscoverRecipeJSONRequestBody = DiscoverRecipeRequest

// PromoteImportCandidateJSONRequestBody defines body for PromoteImportCandidate for application/json ContentType.
type PromoteImportCandidateJSONRequestBody = PromoteCandidateRequest

// UnsetRecipeFavoriteJSONRequestBody defines body for UnsetRecipeFavorite for application/json ContentType.
type UnsetRecipeFavoriteJSONRequestBody = FavoriteNew

// SetRecipeFavoriteJSONRequestBody defines body for SetRecipeFavorite for application/json ContentType.
type SetRecipeFavoriteJSONRequestBody = FavoriteNew

// CreateShoppingListJSONRequestBody defines body for CreateShoppingList for application/json ContentType.
type CreateShoppingListJSONRequestBody = ShoppingListNew

// AddShoppingListItemJSONRequestBody defines body for AddShoppingListItem for application/json ContentType.
type AddShoppingListItemJSONRequestBody = ShoppingListItemNew

// ToggleShoppingListItemJSONRequestBody defines body for ToggleShoppingListItem for application/json ContentType.
type ToggleShoppingListItemJSONRequestBody ToggleShoppingListItemJSONBody
