// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanStatus.
const (
	MealPlanStatusApproved MealPlanStatus = "approved"
	MealPlanStatusArchived MealPlanStatus = "archived"
	MealPlanStatusDraft    MealPlanStatus = "draft"
)

// Valid indicates whether the value is a known member of the MealPlanStatus enum.
func (e MealPlanStatus) Valid() bool {
	switch e {
	case MealPlanStatusApproved:
		return true
	case MealPlanStatusArchived:
		return true
	case MealPlanStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for MealPlanUpdateStatus.
const (
	MealPlanUpdateStatusApproved MealPlanUpdateStatus = "approved"
	MealPlanUpdateStatusArchived MealPlanUpdateStatus = "archived"
	MealPlanUpdateStatusDraft    MealPlanUpdateStatus = "draft"
)

// Valid indicates whether the value is a known member of the MealPlanUpdateStatus enum.
func (e MealPlanUpdateStatus) Valid() bool {
	switch e {
	case MealPlanUpdateStatusApproved:
		return true
	case MealPlanUpdateStatusArchived:
		return true
	case MealPlanUpdateStatusDraft:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status *HealthStatus `json:"status,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// IngredientMapping defines model for IngredientMapping.
type IngredientMapping struct {
	ExternalId *string `json:"external_id,omitempty"`

	// IngredientId canonical ingredient id (see Ingredient.id)
	IngredientId string    `json:"ingredient_id"`
	MealieFoodId string    `json:"mealie_food_id"`
	NeedsReview  bool      `json:"needs_review"`
	SourceName   string    `json:"source_name"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// IngredientMappingResolve defines model for IngredientMappingResolve.
type IngredientMappingResolve struct {
	AcceptableForms *[]string `json:"acceptable_forms,omitempty"`
	IngredientId    string    `json:"ingredient_id"`
	PreferredForm   *string   `json:"preferred_form,omitempty"`
}

// MealEvent defines model for MealEvent.
type MealEvent struct {
	CreatedAt      time.Time          `json:"created_at"`
	Id             int                `json:"id"`
	MealieRecipeId string             `json:"mealie_recipe_id"`
	Reactions      []MealReaction     `json:"reactions"`
	ServedOn       openapi_types.Date `json:"served_on"`
}

// MealEventNew defines model for MealEventNew.
type MealEventNew struct {
	MealieRecipeId string             `json:"mealie_recipe_id"`
	Reactions      *[]MealReaction    `json:"reactions,omitempty"`
	ServedOn       openapi_types.Date `json:"served_on"`
}

// MealPlan defines model for MealPlan.
type MealPlan struct {
	CreatedAt time.Time      `json:"created_at"`
	Id        int            `json:"id"`
	Status    MealPlanStatus `json:"status"`

	// WeekStart Monday of the planned week
	WeekStart openapi_types.Date `json:"week_start"`
}

// MealPlanStatus defines model for MealPlan.Status.
type MealPlanStatus string

// MealPlanCandidate defines model for MealPlanCandidate.
type MealPlanCandidate struct {
	// Breakdown per-signal score breakdown (pref, effort, repeat, school, campaign, familiarity, novelty)
	Breakdown map[string]float64 `json:"breakdown"`
	Feasible  bool               `json:"feasible"`
	Id        int                `json:"id"`
	Rank      int                `json:"rank"`
	Recipe    RecipeRef          `json:"recipe"`
	Score     float64            `json:"score"`
	SlotDate  openapi_types.Date `json:"slot_date"`
}

// MealPlanDecision defines model for MealPlanDecision.
type MealPlanDecision struct {
	DecidedAt      *time.Time         `json:"decided_at,omitempty"`
	MealieRecipeId string             `json:"mealie_recipe_id"`
	PlanId         int                `json:"plan_id"`
	SlotDate       openapi_types.Date `json:"slot_date"`
}

// MealPlanNew defines model for MealPlanNew.
type MealPlanNew struct {
	WeekStart openapi_types.Date `json:"week_start"`
}

// MealPlanUpdate defines model for MealPlanUpdate.
type MealPlanUpdate struct {
	Status *MealPlanUpdateStatus `json:"status,omitempty"`
}

// MealPlanUpdateStatus defines model for MealPlanUpdate.Status.
type MealPlanUpdateStatus string

// MealPlanView defines model for MealPlanView.
type MealPlanView struct {
	Candidates []MealPlanCandidate `json:"candidates"`
	Decisions  *[]MealPlanDecision `json:"decisions,omitempty"`
	Plan       MealPlan            `json:"plan"`
}

// MealReaction defines model for MealReaction.
type MealReaction struct {
	PersonId  string `json:"person_id"`
	Sentiment int    `json:"sentiment"`
}

// Person defines model for Person.
type Person struct {
	CreatedAt time.Time `json:"created_at"`

	// Id canonical id
	Id     string  `json:"id"`
	Name   string  `json:"name"`
	Weight float64 `json:"weight"`
}

// PersonNew defines model for PersonNew.
type PersonNew struct {
	Name   string   `json:"name"`
	Weight *float64 `json:"weight,omitempty"`
}

// PersonPreference defines model for PersonPreference.
type PersonPreference struct {
	Confidence float64 `json:"confidence"`
	PersonId   string  `json:"person_id"`

	// Sentiment -2 (strongly dislike) to 2 (love)
	Sentiment int       `json:"sentiment"`
	Tag       string    `json:"tag"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RecipeRef defines model for RecipeRef.
type RecipeRef struct {
	// Effort 1 (quick) to 3 (intense)
	Effort         int       `json:"effort"`
	LastSyncedAt   time.Time `json:"last_synced_at"`
	MealieRecipeId string    `json:"mealie_recipe_id"`
	Tags           []string  `json:"tags"`
	Title          string    `json:"title"`
}

// ShoppingRequirement defines model for ShoppingRequirement.
type ShoppingRequirement struct {
	AcceptableForms []string `json:"acceptable_forms"`
	Id              int      `json:"id"`
	IngredientId    string   `json:"ingredient_id"`
	PreferredForm   *string  `json:"preferred_form"`
	Quantity        float64  `json:"quantity"`
	Unit            string   `json:"unit"`
}

// PersonId defines model for PersonId.
type PersonId = string

// PlanId defines model for PlanId.
type PlanId = int

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// SetDecisionsJSONBody defines parameters for SetDecisions.
type SetDecisionsJSONBody = []MealPlanDecision

// ListPreferencesParams defines parameters for ListPreferences.
type ListPreferencesParams struct {
	// PersonId filter to one person
	PersonId *string `form:"personId,omitempty" json:"personId,omitempty"`
}

// ResolveIngredientMappingJSONRequestBody defines body for ResolveIngredientMapping for application/json ContentType.
type ResolveIngredientMappingJSONRequestBody = IngredientMappingResolve

// CreateMealEventJSONRequestBody defines body for CreateMealEvent for application/json ContentType.
type CreateMealEventJSONRequestBody = MealEventNew

// CreatePersonJSONRequestBody defines body for CreatePerson for application/json ContentType.
type CreatePersonJSONRequestBody = PersonNew

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = MealPlanNew

// UpdatePlanJSONRequestBody defines body for UpdatePlan for application/json ContentType.
type UpdatePlanJSONRequestBody = MealPlanUpdate

// SetDecisionsJSONRequestBody defines body for SetDecisions for application/json ContentType.
type SetDecisionsJSONRequestBody = SetDecisionsJSONBody
